// @ts-nocheck
import assert from 'node:assert/strict'; import crypto from 'node:crypto'; import http from 'node:http'; import { test } from 'node:test'; import { io as createClient } from 'socket.io-client';
import { app } from '../src/app.js'; import { configureRealtime } from '../src/realtime/index.js'; import { getIdentityRepository, resetIdentityRepository } from '../src/repositories/identityRepository.js'; import { createAccessToken } from '../src/services/tokenService.js'; import { createListing, transitionListing } from '../src/services/listingService.js'; import { findOrCreateConversation } from '../src/services/messagingService.js';
async function identity(name:string){const repository=getIdentityRepository();const user=await repository.createUser({name,roles:['customer'],status:'active',security:{tokenVersion:0},verification:{email:{status:'verified'}},seller:{status:'not_started'}});const session=await repository.createSession({userId:String(user._id),tokenHash:'test',familyId:crypto.randomUUID(),expiresAt:new Date(Date.now()+3600000),lastActiveAt:new Date()});return{id:String(user._id),token:createAccessToken(user,String(session._id))}}
test('authenticated sockets enforce conversation membership and deliver realtime messages',async()=>{resetIdentityRepository();const buyer=await identity('Socket Buyer');const seller=await identity('Socket Seller');const outsider=await identity('Socket Outsider');const draft:any=await createListing(seller.id,{categorySlug:'vehicles',subcategorySlug:'cars',title:'Socket Test Vehicle',description:'A complete listing used to test secure realtime chat.',price:1000000,currency:'PKR',negotiable:false,condition:'used',attributes:{},media:[{url:'https://images.example.test/socket.webp',key:'test/socket',order:0,type:'image',alt:'',isCover:true}],location:{country:'PK',province:'Punjab',city:'Lahore',area:'DHA'}});await transitionListing(seller.id,draft.publicId,'publish');const conversation:any=await findOrCreateConversation(buyer.id,draft.publicId);const server=http.createServer(app);const ioServer=configureRealtime(server);await new Promise<void>((resolve)=>server.listen(0,'127.0.0.1',resolve));const port=(server.address() as any).port;
  const anonymous=createClient(`http://127.0.0.1:${port}`,{autoConnect:false,transports:['websocket']});const rejected=new Promise<void>((resolve,reject)=>{anonymous.on('connect',()=>reject(new Error('anonymous connected')));anonymous.on('connect_error',()=>resolve())});anonymous.connect();await rejected;anonymous.close();
  const buyerSocket=createClient(`http://127.0.0.1:${port}`,{transports:['websocket'],auth:{token:buyer.token}});await new Promise<void>((resolve,reject)=>{buyerSocket.on('connect',()=>resolve());buyerSocket.on('connect_error',reject)});const joined:any=await new Promise((resolve)=>buyerSocket.emit('conversation:join',{conversationId:conversation.id},resolve));assert.equal(joined.ok,true);const sellerSocket=createClient(`http://127.0.0.1:${port}`,{transports:['websocket'],auth:{token:seller.token}});await new Promise<void>((resolve,reject)=>{sellerSocket.on('connect',resolve);sellerSocket.on('connect_error',reject)});const sellerJoined:any=await new Promise((resolve)=>sellerSocket.emit('conversation:join',{conversationId:conversation.id},resolve));assert.equal(sellerJoined.ok,true);
  const typing=new Promise<void>((resolve)=>sellerSocket.once('typing:start',()=>resolve()));buyerSocket.emit('typing:start',{conversationId:conversation.id});await typing;
  const received=new Promise<any>((resolve)=>sellerSocket.once('message:new',resolve));const sent:any=await new Promise((resolve)=>buyerSocket.emit('message:send',{conversationId:conversation.id,message:{text:'Realtime hello',attachments:[],clientId:crypto.randomUUID()}},resolve));assert.equal(sent.ok,true);const incoming=await received;assert.equal(incoming.text,'Realtime hello');const readReceipt=new Promise<void>((resolve)=>buyerSocket.once('message:read',()=>resolve()));sellerSocket.emit('message:read',{conversationId:conversation.id});await readReceipt;
  const outsiderSocket=createClient(`http://127.0.0.1:${port}`,{transports:['websocket'],auth:{token:outsider.token}});await new Promise<void>((resolve,reject)=>{outsiderSocket.on('connect',resolve);outsiderSocket.on('connect_error',reject)});const denied:any=await new Promise((resolve)=>outsiderSocket.emit('conversation:join',{conversationId:conversation.id},resolve));assert.equal(denied.ok,false);buyerSocket.close();sellerSocket.close();outsiderSocket.close();ioServer.close();await new Promise<void>((resolve)=>server.close(()=>resolve()));});
