import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import { beforeEach, test } from 'node:test';
import request from 'supertest';
import { app } from '../src/app.js';
import { getIdentityRepository, resetIdentityRepository } from '../src/repositories/identityRepository.js';
import { getSellerProfileRepository } from '../src/repositories/sellerProfileRepository.js';
import { createAccessToken } from '../src/services/tokenService.js';
import { createListing, adminUpdateListingStatus, getOwnedListing, transitionListing } from '../src/services/listingService.js';
import { assessListing, __resetRiskMemory } from '../src/services/riskAssessmentService.js';
import { __resetBlockMemory } from '../src/services/blockService.js';
import { resetSellerVerificationMemory } from '../src/services/sellerVerificationService.js';
import { resetTrustSafetyMemory } from '../src/services/trustSafetyService.js';
import { resetListingReportMemory } from '../src/services/reportService.js';
import { __resetReviewMemory } from '../src/services/reviewService.js';

async function identity(roles:string[],name=roles[0]){const repo=getIdentityRepository();const user:any=await repo.createUser({name,email:`${crypto.randomUUID()}@example.test`,phone:`+92${Math.floor(1000000000+Math.random()*8999999999)}`,passwordHash:'not-used',roles,status:'active',security:{tokenVersion:0},verification:{email:{status:'verified'}},createdAt:new Date()});const session:any=await repo.createSession({userId:String(user._id),tokenHash:'test',familyId:crypto.randomUUID(),expiresAt:new Date(Date.now()+3600000),lastActiveAt:new Date()});return{id:String(user._id),token:createAccessToken(user,String(session._id)),user}}
async function seller(name:string){const result=await identity(['seller'],name);const slug=`${name.toLowerCase().replace(/[^a-z0-9]+/g,'-')}-${result.id.replaceAll('-','').slice(0,5)}`;await getSellerProfileRepository().upsert(result.id,{displayName:name,publicSlug:slug,description:'QAVLIO seller',location:{country:'PK',city:'Lahore'},verificationStatus:'not_verified',accountType:'individual',isActive:true,safetyStatus:'normal'});return{...result,slug}}
const auth=(token:string)=>({Authorization:`Bearer ${token}`});
const listing=(title:string,description='A complete honest listing with clear item details and condition information.')=>({categorySlug:'vehicles',subcategorySlug:'cars',title,description,price:1500000,currency:'PKR' as const,negotiable:false,condition:'used' as const,attributes:{},media:[{url:`https://images.example.test/${title.replaceAll(' ','-')}.webp`,key:`test/${title.replaceAll(' ','-')}`,order:0,type:'image' as const,alt:title,isCover:true}],location:{country:'PK',province:'Punjab',city:'Lahore',area:'DHA'}});
beforeEach(()=>{resetIdentityRepository();resetSellerVerificationMemory();resetTrustSafetyMemory();__resetRiskMemory();__resetBlockMemory();resetListingReportMemory();__resetReviewMemory()});

test('seller verification is backend-controlled and private documents never leak',async()=>{const owner=await seller('Verification Seller'),moderator=await identity(['moderator'],'Verification Moderator'),admin=await identity(['super_admin'],'Verification Admin'),outsider=await identity(['customer'],'Normal User');await request(app).patch(`/api/v1/admin/sellers/${owner.id}/status`).set(auth(admin.token)).send({verificationStatus:'verified'}).expect(409);await request(app).post('/api/v1/verification/submit').set(auth(owner.token)).send({verificationType:'individual',fullName:'Verification Seller',contactEmail:'seller@example.test',status:'Verified',reviewedBy:owner.id}).expect(422);const submitted=await request(app).post('/api/v1/verification/submit').set(auth(owner.token)).send({verificationType:'individual',fullName:'Verification Seller',contactEmail:'seller@example.test',contactPhone:''}).expect(201);assert.equal(submitted.body.data.status,'Pending');assert.equal(submitted.body.data.reviewedBy,undefined);await request(app).post(`/api/v1/admin/verification/${submitted.body.data.id}/approve`).set(auth(outsider.token)).send({reason:'fake admin action',notes:''}).expect(403);await request(app).post(`/api/v1/admin/verification/${submitted.body.data.id}/request_information`).set(auth(moderator.token)).send({reason:'Please confirm the contact information.',notes:'Private moderator note'}).expect(200);const needs=await request(app).get('/api/v1/verification/status').set(auth(owner.token)).expect(200);assert.equal(needs.body.data.status,'Needs More Information');assert.equal(needs.body.data.rejectionReason,'Please confirm the contact information.');await request(app).post('/api/v1/verification/submit').set(auth(owner.token)).send({verificationType:'individual',fullName:'Verification Seller',contactEmail:'seller@example.test',contactPhone:'+923001111111'}).expect(201);const queue=await request(app).get('/api/v1/admin/verification?status=Pending').set(auth(moderator.token)).expect(200);const current=queue.body.data.verifications.at(-1);const detail=await request(app).get(`/api/v1/admin/verification/${current.id}`).set(auth(moderator.token)).expect(200);assert.doesNotMatch(JSON.stringify(detail.body),/secureStorageReference|private:\/\//);await request(app).post(`/api/v1/admin/verification/${current.id}/approve`).set(auth(moderator.token)).send({reason:'Required profile details reviewed.',notes:''}).expect(200);const publicSeller=await request(app).get(`/api/v1/sellers/${owner.slug}`).expect(200);assert.equal(publicSeller.body.data.verified,true);assert.equal(publicSeller.body.data.verificationStatus,'verified');await request(app).post('/api/v1/verification/documents/intent').set(auth(owner.token)).send({type:'identity_front',fileName:'id.pdf',fileType:'application/pdf',fileSize:1000}).expect(503)});

test('risk engine produces low medium high and critical signals without public score leakage',async()=>{const owner=await seller('Risk Engine Seller');const normal:any=await createListing(owner.id,listing('Normal family car'));const low:any=await assessListing(normal);assert.equal(low.riskLevel,'Low');const contact:any=await createListing(owner.id,listing('Contact payment car','A real car. Pay with JazzCash first and then collect it tomorrow.'));const medium:any=await assessListing(contact);assert.equal(medium.riskLevel,'Medium');await transitionListing(owner.id,normal.publicId,'publish');const duplicate:any=await createListing(owner.id,{...listing('Normal family car'),media:normal.media});const high:any=await assessListing(duplicate);assert.ok(['High','Critical'].includes(high.riskLevel));const prohibited:any=await createListing(owner.id,listing('Forged passport documents','Forged passport and fraudulent document offered immediately.'));const critical:any=await assessListing(prohibited);assert.equal(critical.riskLevel,'Critical');const submitted:any=await transitionListing(owner.id,prohibited.publicId,'publish');assert.equal(submitted.status,'pending');const publicNormal=await request(app).get(`/api/v1/listings/${normal.publicId}`).expect(200);assert.doesNotMatch(JSON.stringify(publicNormal.body),/riskScore|"score"|policy_prohibited/)});

test('reports allow meaningful follow-up, block effects are enforced, and hidden listings leave search',async()=>{const owner=await seller('Reported Seller'),reporter=await identity(['customer'],'Reporter'),item:any=await createListing(owner.id,listing('Reported marketplace car'));await transitionListing(owner.id,item.publicId,'publish');await request(app).post('/api/v1/reports').set(auth(reporter.token)).send({targetType:'listing',targetId:item.publicId,reason:'fraud',description:'The payment request appears suspicious.'}).expect(201);await request(app).post('/api/v1/reports').set(auth(reporter.token)).send({targetType:'listing',targetId:item.publicId,reason:'fraud',description:'Repeated copy'}).expect(409);await request(app).post('/api/v1/reports').set(auth(reporter.token)).send({targetType:'listing',targetId:item.publicId,reason:'wrong-price',description:'The displayed price also appears incorrect.'}).expect(201);const reports=await request(app).get('/api/v1/reports').set(auth(reporter.token)).expect(200);assert.equal(reports.body.data.filter((row:any)=>row.type==='listing').length,2);await request(app).post(`/api/v1/users/${owner.id}/block`).set(auth(reporter.token)).expect(200);await request(app).post(`/api/v1/listings/${item.publicId}/conversation`).set(auth(reporter.token)).expect(403);await request(app).post(`/api/v1/listings/${item.publicId}/block`).set(auth(reporter.token)).expect(200);const search=await request(app).get('/api/v1/search?q=Reported%20marketplace%20car').set(auth(reporter.token)).expect(200);assert.ok(!search.body.data.listings.some((row:any)=>row.publicId===item.publicId));await request(app).delete(`/api/v1/users/${owner.id}/block`).set(auth(reporter.token)).expect(200);await request(app).get('/api/v1/blocked-users').set(auth(reporter.token)).expect(200)});

test('restrictions enforce capabilities and appeals require ownership, new information and human resolution',async()=>{const owner=await seller('Appeal Seller'),other=await seller('Other Seller'),moderator=await identity(['moderator'],'Safety Moderator');const restricted=await request(app).post('/api/v1/admin/restrictions').set(auth(moderator.token)).send({userId:owner.id,type:'LISTING',reason:'Temporary listing review is required.',endAt:new Date(Date.now()+86400000).toISOString()}).expect(201);await request(app).post('/api/v1/listings').set(auth(owner.token)).send(listing('Blocked listing attempt')).expect(403);await request(app).post(`/api/v1/admin/restrictions/${restricted.body.data.id}/revoke`).set(auth(moderator.token)).send({reason:'Review completed'}).expect(200);const item:any=await createListing(owner.id,listing('Appealable listing'));await adminUpdateListingStatus(item.publicId,'rejected','Listing description needs review',moderator.id);await request(app).post('/api/v1/appeals').set(auth(other.token)).send({targetType:'listing',targetId:item.publicId,reason:'Review decision',description:'I want to appeal a listing that is not mine.',evidenceReferences:[]}).expect(404);const appeal=await request(app).post('/api/v1/appeals').set(auth(owner.token)).send({targetType:'listing',targetId:item.publicId,reason:'Information corrected',description:'I have corrected the description and can provide accurate item details.',evidenceReferences:[]}).expect(201);await request(app).post('/api/v1/appeals').set(auth(owner.token)).send({targetType:'listing',targetId:item.publicId,reason:'Again',description:'I have corrected the description and can provide accurate item details.',evidenceReferences:[]}).expect(409);await request(app).post(`/api/v1/admin/appeals/${appeal.body.data.id}/resolve`).set(auth(other.token)).send({action:'accept',note:'fake admin'}).expect(403);await request(app).post(`/api/v1/admin/appeals/${appeal.body.data.id}/resolve`).set(auth(moderator.token)).send({action:'accept',note:'Corrected content should return to review.'}).expect(200);const restored:any=await getOwnedListing(owner.id,item.publicId);assert.equal(restored.status,'pending');assert.equal(restored.moderationState,'Pending Review');const queue=await request(app).get('/api/v1/admin/moderation').set(auth(moderator.token)).expect(200);assert.ok(queue.body.data.summary.appeals>=1)});
