/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: ['class', '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        primary: 'rgb(var(--q-primary) / <alpha-value>)',
        'primary-hover': 'rgb(var(--q-primary-hover) / <alpha-value>)',
        secondary: 'rgb(var(--q-secondary) / <alpha-value>)',
        accent: 'rgb(var(--q-accent) / <alpha-value>)',
        background: 'rgb(var(--q-background) / <alpha-value>)',
        elevated: 'rgb(var(--q-surface-elevated) / <alpha-value>)',
        border: 'rgb(var(--q-border) / <alpha-value>)',
        success: 'rgb(var(--q-success) / <alpha-value>)',
        warning: 'rgb(var(--q-warning) / <alpha-value>)',
        error: 'rgb(var(--q-error) / <alpha-value>)',
        info: 'rgb(var(--q-info) / <alpha-value>)',
        ink: {
          950: 'rgb(var(--q-ink-950) / <alpha-value>)',
          900: 'rgb(var(--q-ink-900) / <alpha-value>)',
          800: 'rgb(var(--q-ink-800) / <alpha-value>)',
          700: 'rgb(var(--q-ink-700) / <alpha-value>)',
        },
        violet: {
          50: 'rgb(var(--q-violet-50) / <alpha-value>)',
          100: 'rgb(var(--q-violet-100) / <alpha-value>)',
          200: 'rgb(var(--q-violet-200) / <alpha-value>)',
          300: 'rgb(var(--q-violet-300) / <alpha-value>)',
          400: 'rgb(var(--q-violet-400) / <alpha-value>)',
          500: 'rgb(var(--q-violet-500) / <alpha-value>)',
          600: 'rgb(var(--q-violet-600) / <alpha-value>)',
          700: 'rgb(var(--q-violet-700) / <alpha-value>)',
          800: 'rgb(var(--q-violet-800) / <alpha-value>)',
          900: 'rgb(var(--q-violet-900) / <alpha-value>)',
        },
        gold: {
          50: 'rgb(var(--q-gold-50) / <alpha-value>)',
          100: 'rgb(var(--q-gold-100) / <alpha-value>)',
          200: 'rgb(var(--q-gold-200) / <alpha-value>)',
          300: 'rgb(var(--q-gold-300) / <alpha-value>)',
          400: 'rgb(var(--q-gold-400) / <alpha-value>)',
          500: 'rgb(var(--q-gold-500) / <alpha-value>)',
          600: 'rgb(var(--q-gold-600) / <alpha-value>)',
        },
        surface: 'rgb(var(--q-background) / <alpha-value>)',
      },
      fontFamily: {
        sans: ['Manrope', 'Inter', 'Noto Sans Arabic', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        // Urdu UI text: clean, compact, highly legible in buttons and controls.
        urdu: ['Noto Sans Arabic', 'Manrope', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        // Urdu display text: traditional Nastaliq, reserved for large headings.
        nastaliq: ['Noto Nastaliq Urdu', 'Noto Sans Arabic', 'serif'],
      },
      fontSize: {
        display: ['clamp(2.55rem, 5vw, 3.75rem)', { lineHeight: '1.02', letterSpacing: '-0.045em', fontWeight: '800' }],
        h1: ['clamp(2rem, 4vw, 3rem)', { lineHeight: '1.08', letterSpacing: '-0.035em', fontWeight: '800' }],
        h2: ['clamp(1.625rem, 3vw, 2.25rem)', { lineHeight: '1.15', letterSpacing: '-0.03em', fontWeight: '800' }],
        h3: ['1.25rem', { lineHeight: '1.35', letterSpacing: '-0.02em', fontWeight: '750' }],
        'body-lg': ['1.0625rem', { lineHeight: '1.75' }],
        body: ['0.9375rem', { lineHeight: '1.7' }],
        'body-sm': ['0.8125rem', { lineHeight: '1.6' }],
        caption: ['0.6875rem', { lineHeight: '1.45' }],
      },
      spacing: {
        18: '4.5rem',
        22: '5.5rem',
        26: '6.5rem',
      },
      boxShadow: {
        sm: 'var(--q-shadow-sm)',
        card: 'var(--q-shadow-card)',
        lg: 'var(--q-shadow-lg)',
        floating: 'var(--q-shadow-floating)',
        float: 'var(--q-shadow-floating)',
      },
      borderRadius: {
        control: 'var(--q-radius-sm)',
        card: 'var(--q-radius-md)',
        panel: 'var(--q-radius-lg)',
        '2xl': 'var(--q-radius-md)',
        '3xl': 'var(--q-radius-xl)',
      },
      transitionDuration: {
        150: '150ms',
        200: '200ms',
        250: '250ms',
        300: '300ms',
        400: '400ms',
      },
      // Deliberate stacking order. Never invent ad-hoc z-index values.
      zIndex: {
        base: '0',
        content: '10',
        raised: '20',
        sticky: '40',
        header: '50',
        dropdown: '55',
        popover: '60',
        drawer: '65',
        modal: '70',
        chatbot: '80',
        toast: '90',
      },
      keyframes: {
        'fade-in': { from: { opacity: '0' }, to: { opacity: '1' } },
        'fade-in-up': { from: { opacity: '0', transform: 'translateY(8px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        'scale-in': { from: { opacity: '0', transform: 'scale(.97)' }, to: { opacity: '1', transform: 'scale(1)' } },
        'thinking-dot': { '0%, 80%, 100%': { opacity: '.25', transform: 'translateY(0)' }, '40%': { opacity: '1', transform: 'translateY(-2px)' } },
      },
      animation: {
        'fade-in': 'fade-in 200ms ease-out both',
        'fade-in-up': 'fade-in-up 250ms ease-out both',
        'scale-in': 'scale-in 200ms ease-out both',
        'thinking-dot': 'thinking-dot 1.2s ease-in-out infinite',
      },
    },
  },
  plugins: [],
};
