import { ArrowLeft, ArrowRight, ImagePlus, LoaderCircle, Star, Trash2, UploadCloud } from 'lucide-react';
import { useRef, useState } from 'react';
import { listingApi } from '../../services/apiClient';
export interface ListingImage { url: string; thumbnailUrl?: string; key: string; width?: number; height?: number; order: number; isCover: boolean; local?: boolean; name?: string; }
export default function ImageUploader({ images, onChange }: { images: ListingImage[]; onChange: (images: ListingImage[]) => void }) {
  const input = useRef<HTMLInputElement>(null); const [dragging, setDragging] = useState(false); const [uploading, setUploading] = useState(0); const [error, setError] = useState('');
  const normalize = (items: ListingImage[]) => items.map((item, order) => ({ ...item, order, isCover: order === 0 }));
  const addFiles = async (files: FileList | File[]) => {
    setError(''); const valid = [...files].filter((file) => ['image/jpeg','image/png','image/webp'].includes(file.type) && file.size <= 8 * 1024 * 1024).slice(0, 12 - images.length);
    if (valid.length !== files.length) setError('Some photos were skipped. Use JPG, PNG or WebP files up to 8 MB.');
    const previews = valid.map((file, index) => ({ url: URL.createObjectURL(file), key: `local-${crypto.randomUUID()}`, order: images.length + index, isCover: images.length + index === 0, local: true, name: file.name })); onChange(normalize([...images, ...previews]));
    let working = normalize([...images, ...previews]); for (let index = 0; index < valid.length; index++) { setUploading(index + 1); try { const uploaded = await listingApi.uploadImage(valid[index]); working = working.map((item) => item.name === valid[index].name && item.local ? { ...uploaded, order: item.order, isCover: item.isCover } : item); onChange(working); } catch (cause) { setError(cause instanceof Error && cause.message.includes('not configured') ? 'Photos are kept in this browser preview. Cloud storage must be configured before publishing.' : 'A photo could not be uploaded. Your local preview is still available.'); } } setUploading(0);
  };
  const move = (index: number, direction: number) => { const next = [...images]; const target = index + direction; if (target < 0 || target >= next.length) return; [next[index], next[target]] = [next[target], next[index]]; onChange(normalize(next)); };
  return <div><h2 className="text-xl font-extrabold">Add great photos</h2><p className="mt-1 text-sm text-slate-500">Add up to 12 photos. The first image is your cover.</p><button type="button" onClick={() => input.current?.click()} onDragOver={(e) => { e.preventDefault(); setDragging(true); }} onDragLeave={() => setDragging(false)} onDrop={(e) => { e.preventDefault(); setDragging(false); void addFiles(e.dataTransfer.files); }} className={`mt-5 flex min-h-36 w-full flex-col items-center justify-center rounded-card border-2 border-dashed p-5 ${dragging ? 'border-violet-500 bg-violet-50' : 'border-slate-300 bg-slate-50'}`}><UploadCloud className="text-violet-600" /><strong className="mt-2 text-sm">Drop photos here or browse</strong><span className="mt-1 text-[11px] text-slate-500">JPG, PNG, WEBP · 8 MB each</span></button><input ref={input} className="sr-only" type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={(e) => e.target.files && void addFiles(e.target.files)} aria-label="Choose listing photos" />
    {uploading > 0 && <p className="mt-3 flex items-center gap-2 text-xs font-bold text-violet-700"><LoaderCircle className="animate-spin" size={14} /> Optimizing and uploading photo {uploading}…</p>}{error && <p role="alert" className="mt-3 rounded-control bg-amber-50 p-3 text-xs font-semibold text-amber-800">{error}</p>}
    <div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-3">{images.map((image, index) => <article key={image.key} className="overflow-hidden rounded-card border bg-white"><div className="relative aspect-[4/3] bg-slate-100"><img src={image.url} alt={`Listing photo ${index + 1}`} className="h-full w-full object-cover" />{index === 0 && <span className="absolute start-2 top-2 inline-flex items-center gap-1 rounded-full bg-ink-950 px-2 py-1 text-[9px] font-extrabold text-white"><Star size={10} /> Cover</span>}</div><div className="flex items-center justify-between p-2"><div><button type="button" onClick={() => move(index, -1)} disabled={index === 0} className="tap-target text-slate-500 disabled:opacity-20" aria-label={`Move photo ${index + 1} left`}><ArrowLeft size={14} /></button><button type="button" onClick={() => move(index, 1)} disabled={index === images.length - 1} className="tap-target text-slate-500 disabled:opacity-20" aria-label={`Move photo ${index + 1} right`}><ArrowRight size={14} /></button></div><button type="button" onClick={() => onChange(normalize(images.filter((_, itemIndex) => itemIndex !== index)))} className="tap-target text-red-600" aria-label={`Remove photo ${index + 1}`}><Trash2 size={14} /></button></div></article>)}{images.length < 12 && images.length > 0 && <button type="button" onClick={() => input.current?.click()} className="grid min-h-36 place-items-center rounded-card border border-dashed border-slate-300 text-xs font-extrabold text-slate-500"><span><ImagePlus className="mx-auto mb-2" /> Add more</span></button>}</div>
  </div>;
}
