import { useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowLeft, ArrowRight, Check, Cloud, LoaderCircle, Save } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { listingApi, monetizationApi } from '../../services/apiClient';
import ListingQuota from '../monetization/ListingQuota';
import AIListingAssistant from '../ai/AIListingAssistant';
import CategorySelector from './CategorySelector';
import DynamicAttributeFields from './DynamicAttributeFields';
import ImageUploader, { type ListingImage } from './ImageUploader';
import ListingPreview from './ListingPreview';
const steps = ['Category', 'Details', 'Photos', 'Location', 'Preview'];
interface FormData { categorySlug: string; subcategorySlug: string; title: string; description: string; price: string; currency: string; negotiable: boolean; condition: string; attributes: Record<string, string | number | boolean>; images: ListingImage[]; location: { country: string; province: string; city: string; area: string }; }
const empty: FormData = { categorySlug: '', subcategorySlug: '', title: '', description: '', price: '', currency: 'PKR', negotiable: false, condition: '', attributes: {}, images: [], location: { country: 'PK', province: 'Punjab', city: '', area: '' } };
export default function ListingWizard({ listingId }: { listingId?: string }) {
  const navigate = useNavigate(); const client = useQueryClient(); const [step, setStep] = useState(0); const [draftId, setDraftId] = useState(listingId || ''); const [data, setData] = useState<FormData>(() => { try { return { ...empty, ...JSON.parse(localStorage.getItem('qavlio-listing-backup') || '{}') }; } catch { return empty; } }); const [saving, setSaving] = useState(false); const [savedAt, setSavedAt] = useState<Date>(); const [error, setError] = useState(''); const [published, setPublished] = useState(false);
  const existing = useQuery({ queryKey: ['seller-listing', listingId], enabled: Boolean(listingId), queryFn: async () => (await listingApi.sellerListing(listingId!)).data });
  const monetization = useQuery({ queryKey: ['monetization-overview'], queryFn: async () => (await monetizationApi.overview()).data });
  useEffect(() => { if (!existing.data) return; const item = existing.data; setDraftId(item.publicId); setData({ categorySlug: item.categorySlug || '', subcategorySlug: item.subcategorySlug || '', title: item.title || '', description: item.description || '', price: String(item.price || ''), currency: item.currency || 'PKR', negotiable: Boolean(item.negotiable), condition: item.condition || '', attributes: item.attributes || {}, images: item.media || [], location: { ...empty.location, ...(item.location || {}) } }); }, [existing.data]);
  const payload = useMemo(() => ({ categorySlug: data.categorySlug || undefined, subcategorySlug: data.subcategorySlug || undefined, title: data.title || undefined, description: data.description || undefined, price: data.price === '' ? undefined : Number(data.price), currency: data.currency, negotiable: data.negotiable, condition: data.condition || undefined, attributes: data.attributes, media: data.images.filter((image) => !image.local).map((image) => ({ url: image.url, thumbnailUrl: image.thumbnailUrl, key: image.key, width: image.width, height: image.height, order: image.order, isCover: image.isCover, alt: data.title })), location: data.location.city || data.location.area ? data.location : undefined }), [data]);
  const save = async (quiet = false) => { if (!quiet) setSaving(true); setError(''); try { const response = draftId ? await listingApi.update(draftId, payload) : await listingApi.create(payload); const id = response.data.publicId; setDraftId(id); setSavedAt(new Date()); localStorage.removeItem('qavlio-listing-backup'); await client.invalidateQueries({ queryKey: ['seller-listings'] }); return id; } catch (cause) { setError(cause instanceof Error ? cause.message : 'We couldn’t save your listing.'); throw cause; } finally { if (!quiet) setSaving(false); } };
  useEffect(() => { localStorage.setItem('qavlio-listing-backup', JSON.stringify(data)); if (!draftId) return; const timer = window.setTimeout(() => { void save(true).catch(() => undefined); }, 2200); return () => window.clearTimeout(timer); }, [data, draftId]); // eslint-disable-line react-hooks/exhaustive-deps
  const validateStep = () => { const messages = [!data.categorySlug ? 'Choose a category.' : '', (!data.title.trim() || data.title.trim().length < 5 || data.description.trim().length < 20 || !data.condition || data.price === '') ? 'Add a title, helpful description, price and condition.' : '', !data.images.length ? 'Add at least one photo.' : '', (!data.location.city || !data.location.area) ? 'Choose a city and area.' : '', '']; const message = messages[step]; setError(message); return !message; };
  const next = () => { if (validateStep()) { setStep((value) => Math.min(4, value + 1)); window.scrollTo({ top: 0, behavior: 'smooth' }); } };
  const publish = async () => { setSaving(true); setError(''); try { if (data.images.some((image) => image.local)) throw new Error('Finish uploading every photo before publishing. You can still save this as a draft.'); const id = await save(true); const publication = await listingApi.transition(id!, 'publish'); if (publication.data.paymentRequired) { navigate(`/checkout/listing?payment=${publication.data.payment.id}`); return; } setPublished(true); localStorage.removeItem('qavlio-listing-backup'); await client.invalidateQueries({ queryKey: ['seller-listings'] }); } catch (cause) { setError(cause instanceof Error ? cause.message : 'We couldn’t publish your listing.'); } finally { setSaving(false); } };
  if (existing.isLoading) return <div className="grid min-h-80 place-items-center"><LoaderCircle className="animate-spin text-violet-600" /></div>;
  if (published) return <div className="mx-auto max-w-2xl rounded-panel border border-emerald-200 bg-white p-8 text-center shadow-card"><span className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-emerald-50 text-emerald-700"><Check size={30} /></span><h1 className="mt-5 text-2xl font-extrabold">Your listing is live!</h1><p className="mt-2 text-sm text-slate-500">Buyers can now discover it in the QAVLIO marketplace.</p><div className="mt-6 flex flex-wrap justify-center gap-2"><Link to={`/seller/listings/${draftId}`} className="rounded-control bg-violet-600 px-5 py-3 text-xs font-extrabold text-white">View listing</Link><button type="button" onClick={() => navigate('/seller/listings/new')} className="rounded-control border px-5 py-3 text-xs font-extrabold">Create another</button></div></div>;
  return <div className="mx-auto max-w-5xl"><div className="flex flex-wrap items-end justify-between gap-3"><div><Link to="/seller/listings" className="inline-flex items-center gap-1 text-xs font-bold text-slate-500"><ArrowLeft size={14} /> My listings</Link><p className="eyebrow mt-4">Seller centre</p><h1 className="mt-1 text-3xl font-extrabold">{listingId ? 'Edit listing' : 'Create a listing'}</h1></div><span className="inline-flex items-center gap-1.5 text-[11px] font-bold text-emerald-700"><Cloud size={14} /> {saving ? 'Saving…' : savedAt ? `Saved at ${savedAt.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}` : 'Local backup ready'}</span></div>
    {!listingId && <div className="mt-6"><ListingQuota quota={monetization.data?.quota}/></div>}
    <ol className="hide-scrollbar mt-7 flex overflow-x-auto rounded-card border bg-white p-2" aria-label="Listing creation progress">{steps.map((label, index) => <li key={label} className="flex min-w-[116px] flex-1 items-center"><button type="button" onClick={() => index <= step && setStep(index)} className={`flex w-full items-center gap-2 rounded-control p-2 text-left ${index === step ? 'bg-violet-50 text-violet-700' : index < step ? 'text-emerald-700' : 'text-slate-400'}`} aria-current={index === step ? 'step' : undefined}><span className={`grid h-6 w-6 place-items-center rounded-full text-[10px] font-extrabold ${index === step ? 'bg-violet-600 text-white' : index < step ? 'bg-emerald-100' : 'bg-slate-100'}`}>{index < step ? <Check size={12} /> : index + 1}</span><span className="text-[10px] font-extrabold">{label}</span></button></li>)}</ol>
    <section className="mt-5 rounded-panel border border-ink-900/10 bg-white p-5 shadow-sm sm:p-7">{step === 0 && <CategorySelector category={data.categorySlug} subcategory={data.subcategorySlug} onChange={(category, subcategory = '') => setData({ ...data, categorySlug: category, subcategorySlug: subcategory, attributes: {} })} />}{step === 1 && <><Details data={data} setData={setData} /><div className="mt-5"><AIListingAssistant title={data.title} description={data.description} category={data.categorySlug} subcategory={data.subcategorySlug} condition={data.condition} price={data.price ? Number(data.price) : undefined} imageCount={data.images.length} attributes={Object.fromEntries(Object.entries(data.attributes).map(([key, value]) => [key, String(value)]))} facts={{ condition: data.condition, price: data.price, location: data.location.city }} onApplyTitle={(title) => setData({ ...data, title })} onApplyDescription={(description) => setData({ ...data, description })} onApplyCategory={(category, subcategory) => setData({ ...data, categorySlug: category, subcategorySlug: subcategory || data.subcategorySlug, attributes: {} })} onApplyAttributes={(attributes) => setData({ ...data, attributes: { ...data.attributes, ...attributes } })} /></div></>}{step === 2 && <ImageUploader images={data.images} onChange={(images) => setData({ ...data, images })} />}{step === 3 && <Location data={data} setData={setData} />}{step === 4 && <ListingPreview data={data} />}{error && <p role="alert" className="mt-5 rounded-control bg-red-50 p-3 text-xs font-bold text-red-700">{error}</p>}<div className="sticky bottom-0 -mx-5 mt-7 flex items-center justify-between gap-2 border-t bg-white/95 px-5 pt-5 backdrop-blur sm:-mx-7 sm:px-7"><button type="button" disabled={step === 0} onClick={() => setStep((value) => value - 1)} className="inline-flex h-11 items-center gap-1 rounded-control px-3 text-xs font-extrabold disabled:opacity-30"><ArrowLeft size={15} /> Back</button><div className="ml-auto flex gap-2"><button type="button" onClick={() => void save().catch(() => undefined)} disabled={saving} className="inline-flex h-11 items-center gap-2 rounded-control border px-4 text-xs font-extrabold"><Save size={14} /> <span className="hidden sm:inline">Save draft</span></button>{step < 4 ? <button type="button" onClick={next} className="inline-flex h-11 items-center gap-2 rounded-control bg-violet-600 px-5 text-xs font-extrabold text-white">Continue <ArrowRight size={15} /></button> : <button type="button" onClick={() => void publish()} disabled={saving} className="inline-flex h-11 items-center gap-2 rounded-control bg-emerald-600 px-5 text-xs font-extrabold text-white">{saving && <LoaderCircle size={14} className="animate-spin" />} Publish listing</button>}</div></div></section>
  </div>;
}
function Details({ data, setData }: { data: FormData; setData: (data: FormData) => void }) { return <div><h2 className="text-xl font-extrabold">Tell buyers about it</h2><p className="mt-1 text-sm text-slate-500">Be clear, useful and honest.</p><div className="mt-5 grid gap-5"><label className="text-xs font-extrabold">Title <span className="text-red-500">*</span><input className="input-base mt-2" value={data.title} onChange={(e) => setData({ ...data, title: e.target.value })} maxLength={100} placeholder="e.g. iPhone 15 Pro 256GB in excellent condition" /><span className="mt-1 block text-right text-[10px] text-slate-400">{data.title.length}/100</span></label><label className="text-xs font-extrabold">Description <span className="text-red-500">*</span><textarea className="input-base mt-2 min-h-40 resize-y py-3" value={data.description} onChange={(e) => setData({ ...data, description: e.target.value })} maxLength={10000} placeholder="Describe features, history, condition and what is included." /><span className="mt-1 block text-right text-[10px] text-slate-400">{data.description.length}/10,000</span></label><div className="grid gap-4 sm:grid-cols-2"><label className="text-xs font-extrabold">Price<div className="mt-2 flex"><span className="grid h-12 place-items-center rounded-l-control border border-r-0 bg-slate-50 px-3 text-xs font-bold">PKR</span><input type="number" min="0" max="1000000000000" className="input-base rounded-l-none" value={data.price} onChange={(e) => setData({ ...data, price: e.target.value })} /></div></label><label className="text-xs font-extrabold">Condition<select className="input-base mt-2" value={data.condition} onChange={(e) => setData({ ...data, condition: e.target.value })}><option value="">Select condition</option><option value="new">New</option><option value="like-new">Like New</option><option value="used">Used</option><option value="refurbished">Refurbished</option><option value="for-parts">For Parts</option></select></label></div><label className="flex items-center gap-3 rounded-control border p-4 text-xs font-bold"><input type="checkbox" checked={data.negotiable} onChange={(e) => setData({ ...data, negotiable: e.target.checked })} className="h-4 w-4 accent-violet-600" /> Price is negotiable</label></div><DynamicAttributeFields category={data.categorySlug} values={data.attributes} onChange={(key, value) => setData({ ...data, attributes: { ...data.attributes, [key]: value } })} /></div>; }
function Location({ data, setData }: { data: FormData; setData: (data: FormData) => void }) { const cities = ['Islamabad','Rawalpindi','Lahore','Karachi','Peshawar','Quetta','Multan','Faisalabad']; return <div><h2 className="text-xl font-extrabold">Where is the item?</h2><p className="mt-1 text-sm text-slate-500">Only an approximate area is shown publicly—never a private address.</p><div className="mt-6 grid gap-5 sm:grid-cols-2"><label className="text-xs font-extrabold">Country<select className="input-base mt-2" value="PK" disabled><option value="PK">Pakistan</option></select></label><label className="text-xs font-extrabold">Province<input className="input-base mt-2" value={data.location.province} onChange={(e) => setData({ ...data, location: { ...data.location, province: e.target.value } })} /></label><label className="text-xs font-extrabold">City <span className="text-red-500">*</span><select className="input-base mt-2" value={data.location.city} onChange={(e) => setData({ ...data, location: { ...data.location, city: e.target.value } })}><option value="">Choose city</option>{cities.map((city) => <option key={city}>{city}</option>)}</select></label><label className="text-xs font-extrabold">Area / locality <span className="text-red-500">*</span><input className="input-base mt-2" value={data.location.area} onChange={(e) => setData({ ...data, location: { ...data.location, area: e.target.value } })} placeholder="e.g. Bahria Town" /></label></div></div>; }
