import { useMutation, useQuery } from '@tanstack/react-query';
import { ArrowLeft } from 'lucide-react';
import { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import DashboardLayout from '../../layouts/DashboardLayout';
import PaymentStatus from '../../components/payments/PaymentStatus';
import Receipt from '../../components/payments/Receipt';
import { monetizationApi, paymentApi } from '../../services/apiClient';
import { formatPrice } from '../../utils/formatters';
import { useDocumentTitle } from '../../hooks/useDocumentTitle';
export default function PaymentDetailPage(){const{id=''}=useParams();const[refundOpen,setRefundOpen]=useState(false);const[reason,setReason]=useState('');useDocumentTitle('Transaction detail');const query=useQuery({queryKey:['seller-payment',id],queryFn:async()=>(await paymentApi.sellerPayment(id)).data});const refund=useMutation({mutationFn:()=>monetizationApi.requestRefund(id,reason),onSuccess:()=>setRefundOpen(false)});if(query.isLoading)return <DashboardLayout role="seller"><div className="h-80 animate-pulse rounded-panel bg-slate-200"/></DashboardLayout>;if(!query.data)return <DashboardLayout role="seller"><h1>Transaction not found</h1></DashboardLayout>;const{payment,transaction,receipt}=query.data;return <DashboardLayout role="seller"><div className="mx-auto max-w-3xl"><Link to="/seller/transactions" className="inline-flex items-center gap-1 text-xs font-bold text-slate-500"><ArrowLeft size={14}/>Transactions</Link><header className="mt-5"><p className="eyebrow">Transaction detail</p><div className="mt-2 flex items-center justify-between gap-3"><h1 className="text-3xl font-extrabold">{payment.metadata?.listingTitle||payment.metadata?.packageSnapshot?.name||'QAVLIO service'}</h1><PaymentStatus status={payment.status}/></div></header><section className="mt-6 rounded-panel border bg-white p-6"><dl className="grid gap-5 sm:grid-cols-2">{[['Payment ID',payment.id],['Reference',payment.reference],['Date',new Date(payment.createdAt).toLocaleString()],['Type',payment.type.replace('_',' ')],['Amount',formatPrice(payment.amount,payment.currency)],['Currency',payment.currency],['Transaction ID',transaction?.reference||'Pending'],['Status',payment.status]].map(([label,value])=><div key={label}><dt className="text-[10px] font-bold uppercase text-slate-400">{label}</dt><dd className="mt-1 break-all text-sm font-extrabold capitalize">{value}</dd></div>)}</dl>{payment.status==='paid'&&!refund.data&&<button onClick={()=>setRefundOpen(!refundOpen)} className="mt-6 text-xs font-bold text-violet-700">Request refund review</button>}{refund.data&&<p role="status" className="mt-6 rounded-card bg-amber-50 p-4 text-xs font-bold text-amber-800">Refund request submitted: {refund.data.data.status}. This does not issue a refund automatically.</p>}{refundOpen&&<div className="mt-4 rounded-card border bg-slate-50 p-4"><label className="text-xs font-extrabold">Reason for review<textarea value={reason} onChange={e=>setReason(e.target.value)} className="input-base mt-2 min-h-24 py-3" maxLength={1000}/></label><button onClick={()=>refund.mutate()} disabled={reason.trim().length<10||refund.isPending} className="mt-3 h-10 rounded-control bg-violet-600 px-4 text-xs font-extrabold text-white disabled:opacity-50">Submit request</button>{refund.error&&<p role="alert" className="mt-2 text-xs font-bold text-red-600">{refund.error.message}</p>}</div>}</section>{receipt&&<div className="mt-5"><Receipt receipt={receipt}/></div>}</div></DashboardLayout>}
