import { useQuery } from '@tanstack/react-query';
import { BarChart3, Megaphone, Plus } from 'lucide-react';
import { Link, useSearchParams } from 'react-router-dom';
import DashboardLayout from '../../layouts/DashboardLayout';
import PaymentStatus from '../../components/payments/PaymentStatus';
import { monetizationApi, promotionApi } from '../../services/apiClient';
import { formatPrice } from '../../utils/formatters';
import { useDocumentTitle } from '../../hooks/useDocumentTitle';

export default function SellerPromotionsPage(){useDocumentTitle('Promotions');const[params]=useSearchParams();const query=useQuery({queryKey:['seller-promotions'],queryFn:async()=>(await promotionApi.seller()).data});const analytics=useQuery({queryKey:['promotion-analytics'],queryFn:async()=>(await monetizationApi.promotionAnalytics()).data});const rows=query.data||[];const groups={active:rows.filter((x:any)=>x.status==='active'),scheduled:rows.filter((x:any)=>x.status==='pending'),expired:rows.filter((x:any)=>['expired','cancelled','refunded'].includes(x.status))};const spend=rows.filter((x:any)=>x.paidWith==='payment'&&x.status!=='refunded').reduce((sum:number,x:any)=>sum+Number(x.price),0);return <DashboardLayout role="seller"><div className="flex flex-wrap items-end justify-between gap-3"><header><p className="eyebrow">Paid visibility</p><h1 className="mt-2 text-3xl font-extrabold">Promotions</h1><p className="mt-2 text-sm text-slate-500">Active, scheduled and expired placements with real tracked performance.</p></header><Link to="/seller/listings" className="inline-flex h-11 items-center gap-2 rounded-control bg-violet-600 px-5 text-xs font-extrabold text-white"><Plus size={15}/>Promote a listing</Link></div>{params.get('activated')&&<p role="status" className="mt-5 rounded-card bg-emerald-50 p-4 text-xs font-bold text-emerald-800">Your promotion is now active.</p>}
<section className="mt-6 grid grid-cols-2 gap-3 xl:grid-cols-5">{[['Active',groups.active.length],['Scheduled',groups.scheduled.length],['Expired',groups.expired.length],['Promotion spend',formatPrice(spend)],['Tracked clicks',analytics.data?.summary?.clicks||0]].map(([label,value])=><article key={label} className="rounded-card border bg-white p-4"><p className="text-xl font-extrabold">{value}</p><p className="mt-1 text-[9px] font-bold text-slate-500">{label}</p></article>)}</section>
{query.isLoading?<div className="mt-6 h-56 animate-pulse rounded-panel bg-slate-200"/>:!rows.length?<div className="mt-6 rounded-panel border border-dashed bg-white p-12 text-center"><Megaphone className="mx-auto text-violet-400"/><h2 className="mt-4 font-extrabold">No promotions yet</h2><p className="mt-2 text-xs text-slate-500">Open a published listing to review available options.</p></div>:<div className="mt-6 space-y-7">{Object.entries(groups).map(([group,items]:any)=>items.length?<section key={group}><h2 className="text-sm font-extrabold capitalize">{group} promotions</h2><div className="mt-3 grid gap-3">{items.map((item:any)=>{const metric=analytics.data?.promotions?.find((x:any)=>x.id===item.id);return <article key={item.id} className="rounded-card border bg-white p-5"><div className="flex flex-wrap items-center gap-4"><span className="grid h-10 w-10 place-items-center rounded-xl bg-violet-50 text-violet-600"><Megaphone size={18}/></span><div className="min-w-0 flex-1"><h3 className="text-sm font-extrabold">{item.promotionType?.replace('_',' ')||item.type} promotion</h3><p className="mt-1 text-[10px] text-slate-500">{item.listingPublicId} · {item.paidWith==='credits'?'Paid with credits':formatPrice(item.price,item.currency)}</p></div><PaymentStatus status={item.status}/>{item.status==='active'&&<button onClick={()=>void promotionApi.cancel(item.id).then(()=>query.refetch())} className="text-xs font-bold text-red-600">Cancel</button>}</div>{metric&&<div className="mt-4 grid grid-cols-5 gap-2 border-t pt-4">{[['Impressions',metric.impressions],['Clicks',metric.clicks],['Views',metric.views],['Favorites',metric.favorites],['Messages',metric.messages]].map(([label,value])=><div key={label} className="text-center"><strong className="block text-sm">{value}</strong><span className="text-[8px] text-slate-400">{label}</span></div>)}</div>}</article>})}</div></section>:null)}</div>}
<div className="mt-7 flex items-center gap-2 text-[10px] text-slate-400"><BarChart3 size={13}/>Promotion performance contains deduplicated tracked events, not estimated ROI.</div></DashboardLayout>}
