import { useQuery } from '@tanstack/react-query';
import { BarChart3, Eye, Heart, MessageCircle, MousePointerClick, Star } from 'lucide-react';
import { Link } from 'react-router-dom';
import DashboardLayout from '../../layouts/DashboardLayout';
import { monetizationApi } from '../../services/apiClient';
import { useDocumentTitle } from '../../hooks/useDocumentTitle';

export default function SellerAnalyticsPage(){useDocumentTitle('Seller analytics');const query=useQuery({queryKey:['seller-analytics'],queryFn:async()=>(await monetizationApi.analytics()).data});const data=query.data;const cards=[[Eye,'Listing views',data?.summary?.views||0],[Heart,'Favorites',data?.summary?.favorites||0],[MessageCircle,'Messages',data?.summary?.messages||0],[MousePointerClick,'Promotion clicks',data?.promotionPerformance?.summary?.clicks||0]];return <DashboardLayout role="seller"><header><p className="eyebrow">Measured marketplace activity</p><h1 className="mt-2 text-3xl font-extrabold">Seller analytics</h1><p className="mt-2 text-sm text-slate-500">Only activity QAVLIO actually tracks is shown here. We do not estimate ROI.</p></header>{query.isLoading?<div className="mt-6 h-80 animate-pulse rounded-panel bg-slate-200"/>:<><section className="mt-6 grid grid-cols-2 gap-3 xl:grid-cols-4">{cards.map(([Icon,label,value]:any)=><article key={label} className="rounded-card border bg-white p-5"><Icon size={18} className="text-violet-600"/><p className="mt-3 text-2xl font-extrabold">{Number(value).toLocaleString()}</p><p className="mt-1 text-[10px] font-bold text-slate-500">{label}</p></article>)}</section>
<section className="mt-6 rounded-panel border bg-white p-5 sm:p-7"><div className="flex items-center gap-2"><BarChart3 className="text-violet-600" size={19}/><h2 className="font-extrabold">Promotion performance</h2></div>{!data?.promotionPerformance?.promotions?.length?<p className="mt-5 text-xs text-slate-500">No promotion events have been recorded yet.</p>:<div className="mt-5 overflow-x-auto"><table className="w-full min-w-[700px] text-left text-xs"><thead className="text-[9px] uppercase text-slate-500"><tr>{['Listing','Type','Impressions','Clicks','Views','Favorites','Messages'].map(h=><th className="px-3 py-2" key={h}>{h}</th>)}</tr></thead><tbody>{data.promotionPerformance.promotions.map((item:any)=><tr key={item.id} className="border-t"><td className="px-3 py-4"><Link className="font-bold text-violet-700" to={`/seller/listings/${item.listingPublicId}`}>{item.listingPublicId}</Link></td><td className="px-3">{item.promotionType}</td><td className="px-3">{item.impressions}</td><td className="px-3">{item.clicks}</td><td className="px-3">{item.views}</td><td className="px-3">{item.favorites}</td><td className="px-3">{item.messages}</td></tr>)}</tbody></table></div>}</section>
<section className="mt-6 rounded-panel border bg-white p-5 sm:p-7"><h2 className="flex items-center gap-2 font-extrabold"><Star size={18} className="text-violet-600"/>Top listings</h2><div className="mt-4 divide-y">{data?.topListings?.map((item:any)=><Link to={`/seller/listings/${item.publicId}`} key={item.publicId} className="flex items-center gap-4 py-3 text-xs"><strong className="min-w-0 flex-1 truncate">{item.title}</strong><span className="text-slate-500">{item.views} views</span><span className="text-slate-500">{item.favorites} saves</span></Link>)}</div></section></>}</DashboardLayout>}
