import { useQuery } from '@tanstack/react-query';
import { Megaphone } from 'lucide-react';
import { EmptyState } from '../ui/EmptyState';
import { useTranslation } from '../../i18n';
import { promotionApi } from '../../services/apiClient';
import type { Listing } from '../../types/marketplace';
import ListingSection from './ListingSection';
import SectionHeading from '../ui/SectionHeading';

function normalize(item:any,index:number):Listing { const image=item.coverImage||item.media?.[0]?.url||''; const id=item.publicId||item._id; return { id,slug:item.slug||'listing',title:item.title,price:Number(item.price?.$numberDecimal||item.price||0),currency:item.currency||'PKR',image,imageSrcSet:item.media?.[0]?.thumbnailUrl?`${item.media[0].thumbnailUrl} 480w, ${image} 960w`:'',imageAlt:item.media?.[0]?.alt||item.title,location:[item.location?.area,item.location?.city].filter(Boolean).join(', '),postedAt:item.publishedAt?new Date(item.publishedAt).toLocaleDateString():'Recently',category:item.categorySlug?.replaceAll('-',' ')||'Marketplace',condition:(item.condition||'used').replaceAll('-',' '),featured:item.promotion?.label==='Featured',sponsored:true,promotionLabel:item.promotion?.label||'Sponsored',promotionPlacement:item.promotion?.placement||'homepage',urgent:item.promotion?.label==='Urgent',verified:false,seller:{name:'QAVLIO seller',initials:'QS',rating:0,memberSince:''},discoveryTags:index===0?['recommended']:[] }; }
export default function PromotedListings({placement,title,eyebrow,description}:{placement:'homepage'|'featured';title:string;eyebrow:string;description:string}){const{t}=useTranslation();const query=useQuery({queryKey:['promotion-placement',placement],queryFn:async()=>(await promotionApi.placement(placement)).data});if(query.isLoading)return <section className="container-shell pb-12"><div className="h-64 animate-pulse rounded-panel bg-slate-100"/></section>;if(!query.data?.length)return <section className={placement==='homepage'?'border-y border-violet-100 bg-violet-50/70 py-12 sm:py-16':'pb-12 sm:pb-16'}><div className="container-shell"><SectionHeading eyebrow={eyebrow} title={title} description={description}/><EmptyState icon={Megaphone} title={t('empty.title')} description={t('empty.promotions')} action={{ label: t('empty.exploreMarketplace'), to: '/marketplace' }} /></div></section>;return <ListingSection eyebrow={eyebrow} title={title} description={description} listings={query.data.map(normalize)} variant={placement==='featured'?'featured':'sponsored'} promoted={placement==='homepage'}/>}
