import React from 'react';
import { BarChart3, CreditCard, ListChecks, Settings, ShieldCheck, UsersRound } from 'lucide-react';
import DashboardHeading from '../../components/dashboard/DashboardHeading';
import { Button } from '../../components/ui/Button';
import { useDocumentTitle } from '../../hooks/useDocumentTitle';
import DashboardLayout from '../../layouts/DashboardLayout';

const modules = [{ icon: UsersRound, title: 'User management', body: 'Search identities, review verification, and apply confirmed account actions.', to: '/admin/users', live: true }, { icon: ShieldCheck, title: 'Moderation', body: 'Reports, evidence controls, appeals, and reviewed decisions.', to: '/admin/moderation' }, { icon: ListChecks, title: 'Listings', body: 'Listing ownership, lifecycle, policy, and moderation state.', to: '/admin/listings' }, { icon: CreditCard, title: 'Revenue', body: 'Ledger-backed fees, promotions, advertisements, and reconciliation.', to: '/admin/revenue' }, { icon: BarChart3, title: 'Analytics', body: 'Identity, supply, trust, support, and commercial health.', to: '/admin/analytics' }, { icon: Settings, title: 'System settings', body: 'Versioned categories, pricing, languages, flags, and provider configuration.', to: '/admin/settings' }];

export default function AdminDashboardPage() {
  useDocumentTitle('Admin dashboard');
  return <DashboardLayout role="admin"><DashboardHeading eyebrow="Administration" title="Identity & platform operations" description="Privileged routes use server-side role checks, active session validation, explicit confirmation, and security audit events." action={<span className="inline-flex items-center gap-2 rounded-full bg-emerald-50 px-3 py-2 text-[10px] font-extrabold text-emerald-700"><ShieldCheck size={14} /> Admin session verified</span>} /><section className="rounded-2xl border border-ink-900/10 bg-white p-5 shadow-sm sm:p-7"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{modules.map(({ icon: Icon,title,body,to,live }) => <article key={title} className="relative rounded-2xl border border-slate-200 p-5">{live && <span className="absolute right-4 top-4 rounded-full bg-emerald-50 px-2 py-1 text-[8px] font-extrabold text-emerald-700">PHASE 2 LIVE</span>}<span className="grid h-11 w-11 place-items-center rounded-xl bg-violet-100 text-violet-700"><Icon size={19} /></span><h2 className="mt-4 text-sm font-extrabold">{title}</h2><p className="mt-2 min-h-12 text-[10px] leading-5 text-slate-500">{body}</p><Button to={to} variant={live ? 'primary' : 'secondary'} size="sm" className="mt-4">{live ? 'Open user management' : 'View foundation'}</Button></article>)}</div></section><section className="mt-5 rounded-2xl bg-ink-950 p-6 text-white"><p className="text-[10px] font-extrabold uppercase tracking-wider text-gold-300">No client-side trust</p><h2 className="mt-2 text-lg font-extrabold">Admin visibility is not a frontend role check.</h2><p className="mt-2 max-w-3xl text-xs leading-5 text-white/55">Every admin API call verifies the signed access token, active server session, current account status, current database roles, and resource policy. Role or status changes increment the token version and revoke sessions.</p></section></DashboardLayout>;
}
