import React from 'react';
import { Bell, Heart, MessageCircle, Search, ShieldCheck, UserRound } from 'lucide-react';
import { useAuth } from '../../auth/AuthProvider';
import DashboardHeading from '../../components/dashboard/DashboardHeading';
import VerificationBadge from '../../components/account/VerificationBadge';
import { Button } from '../../components/ui/Button';
import { useDocumentTitle } from '../../hooks/useDocumentTitle';
import DashboardLayout from '../../layouts/DashboardLayout';

const sections = [{ icon: Heart, title: 'Favorites', body: 'Saved listing persistence arrives with marketplace listings.', to: '/saved' }, { icon: Search, title: 'Saved searches', body: 'Search criteria and alerts arrive with discovery.', to: '/dashboard/saved-searches' }, { icon: MessageCircle, title: 'My chats', body: 'Protected identity is ready; realtime chat comes later.', to: '/messages' }, { icon: Bell, title: 'Notifications', body: 'Configure delivery channels and security alerts now.', to: '/account/notifications' }];

export default function CustomerDashboardPage() {
  const { user } = useAuth(); useDocumentTitle('Customer dashboard'); const verification = user.verification || {};
  return <DashboardLayout role="customer"><DashboardHeading eyebrow="Customer dashboard" title={`Welcome, ${user.name?.split(' ')[0] || 'member'}`} description="Your secure QAVLIO identity, trust status, and marketplace entry points." action={<Button to="/browse" variant="secondary"><Search size={16} /> Find something</Button>} /><div className="grid gap-5 xl:grid-cols-[1fr_320px]"><section className="rounded-2xl border border-ink-900/10 bg-white p-5 shadow-sm sm:p-7"><div className="flex items-center gap-3"><span className="grid h-12 w-12 place-items-center rounded-xl bg-violet-100 text-sm font-extrabold text-violet-700">{user.name?.split(' ').map((part) => part[0]).slice(0,2).join('')}</span><div><h2 className="text-base font-extrabold">Identity overview</h2><p className="mt-1 text-[10px] font-semibold text-slate-400">@{user.username} · {user.location?.city || 'Location not set'}</p></div></div><div className="mt-5 flex flex-wrap gap-2"><VerificationBadge label="Email" status={verification.email?.status} /><VerificationBadge label="Phone" status={verification.phone?.status} /><VerificationBadge label="Identity" status={verification.identity?.status} /></div><div className="mt-6 grid gap-3 sm:grid-cols-2">{sections.map(({ icon: Icon,title,body,to }) => <article key={title} className="rounded-xl border border-slate-200 p-4"><Icon size={18} className="text-violet-600" /><h3 className="mt-3 text-sm font-extrabold">{title}</h3><p className="mt-2 min-h-10 text-[10px] leading-5 text-slate-500">{body}</p><Button to={to} variant="ghost" size="sm" className="mt-2 !px-0">Open section</Button></article>)}</div></section><aside className="space-y-4"><section className="rounded-2xl bg-gradient-to-br from-violet-600 to-violet-800 p-5 text-white shadow-card"><ShieldCheck className="text-gold-300" /><p className="mt-4 text-xs font-extrabold uppercase tracking-wider text-gold-300">Account protection</p><h2 className="mt-2 text-lg font-extrabold">Review active sessions</h2><p className="mt-2 text-xs leading-5 text-white/60">See every signed-in device and revoke access you do not recognize.</p><Button to="/account/security" variant="gold" size="sm" className="mt-4">Security centre</Button></section><section className="rounded-2xl border border-ink-900/10 bg-white p-5"><UserRound className="text-violet-600" /><h2 className="mt-4 text-sm font-extrabold">Complete your profile</h2><p className="mt-2 text-[10px] leading-5 text-slate-500">Add an about section, area, and phone verification to help future trading partners understand who they are dealing with.</p><Button to="/account/profile" variant="secondary" size="sm" className="mt-4">Edit profile</Button></section></aside></div></DashboardLayout>;
}
