import React from 'react';
import { useQuery } from '@tanstack/react-query';
import { BarChart3, Coins, Eye, Heart, MessageCircle, PackageCheck, Plus, Rocket } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useAuth } from '../../auth/AuthProvider';
import CreditBalance from '../../components/monetization/CreditBalance';
import ListingQuota from '../../components/monetization/ListingQuota';
import DashboardHeading from '../../components/dashboard/DashboardHeading';
import { Button } from '../../components/ui/Button';
import { useDocumentTitle } from '../../hooks/useDocumentTitle';
import DashboardLayout from '../../layouts/DashboardLayout';
import { listingApi, monetizationApi, paymentApi } from '../../services/apiClient';
import TransactionTable from '../../components/monetization/TransactionTable';

export default function SellerDashboardPage(){const{user}=useAuth();useDocumentTitle('Seller dashboard');const listings=useQuery({queryKey:['seller-listings','dashboard'],queryFn:async()=>(await listingApi.sellerListings('page=1&limit=5')).data});const billing=useQuery({queryKey:['seller-payments','dashboard'],queryFn:async()=>(await paymentApi.sellerPayments('page=1&limit=3')).data});const monetization=useQuery({queryKey:['monetization-overview'],queryFn:async()=>(await monetizationApi.overview()).data});const summary=listings.data?.summary||{};const cards=[[PackageCheck,'Active listings',summary.active||0],[Eye,'Listing views',summary.views||0],[Heart,'Favorites',summary.favorites||0],[MessageCircle,'Messages',summary.messages||0]];return <DashboardLayout role="seller"><DashboardHeading eyebrow="Seller overview" title="Your seller workspace" description={`Welcome back, ${user.name.split(' ')[0]}. Manage inventory, credits and measured buyer activity.`} action={<Button to="/seller/listings/new" variant="gold"><Plus size={16}/>Create listing</Button>}/>
<div className="grid grid-cols-2 gap-3 xl:grid-cols-4">{cards.map(([Icon,label,value])=><article key={label} className="rounded-card border bg-white p-5 shadow-sm"><span className="grid h-10 w-10 place-items-center rounded-xl bg-violet-50 text-violet-600"><Icon size={19}/></span><p className="mt-4 text-2xl font-extrabold">{Number(value).toLocaleString()}</p><p className="mt-1 text-[10px] font-bold text-slate-500">{label}</p></article>)}</div>
<div className="mt-5 grid gap-4 lg:grid-cols-2"><ListingQuota quota={monetization.data?.quota}/><CreditBalance wallet={monetization.data?.wallet}/></div>
<section className="mt-6"><h2 className="text-sm font-extrabold">Quick actions</h2><div className="mt-3 grid grid-cols-2 gap-3 lg:grid-cols-4">{[[Plus,'Create listing','/seller/listings/new'],[Rocket,'Promote listing','/seller/listings'],[Coins,'Buy credits','/seller/packages'],[BarChart3,'View analytics','/seller/analytics']].map(([Icon,label,to])=><Link key={label} to={to} className="flex items-center gap-3 rounded-card border bg-white p-4 text-xs font-extrabold hover:border-violet-300"><span className="grid h-9 w-9 place-items-center rounded-xl bg-violet-50 text-violet-600"><Icon size={17}/></span>{label}</Link>)}</div></section>
<div className="mt-6 grid gap-5 xl:grid-cols-[1fr_340px]"><section><div className="mb-3 flex items-center justify-between"><h2 className="text-sm font-extrabold">Recent transactions</h2><Link to="/seller/transactions" className="text-xs font-bold text-violet-700">View all</Link></div>{billing.data?.payments?.length?<TransactionTable payments={billing.data.payments}/>:<div className="rounded-card border border-dashed bg-white p-8 text-center text-xs text-slate-500">No transactions yet.</div>}</section><section className="rounded-panel border bg-white p-5"><div className="flex items-center justify-between"><h2 className="text-sm font-extrabold">Recent listings</h2><Link to="/seller/listings" className="text-[10px] font-bold text-violet-700">View all</Link></div>{!listings.data?.listings?.length?<div className="mt-5 text-xs text-slate-500">Create your first listing to get started.</div>:<div className="mt-4 divide-y">{listings.data.listings.map(item=><Link to={`/seller/listings/${item.publicId}`} key={item.publicId} className="flex items-center gap-3 py-3"><div className="h-11 w-14 rounded-lg bg-slate-100">{item.media?.[0]&&<img src={item.media[0].url} alt="" className="h-full w-full rounded-lg object-cover"/>}</div><div className="min-w-0 flex-1"><p className="truncate text-xs font-extrabold">{item.title||'Untitled draft'}</p><p className="mt-1 text-[9px] capitalize text-slate-400">{item.status} · {item.viewCount||0} views</p></div></Link>)}</div>}</section></div>
</DashboardLayout>}
