import { CheckCircle2, KeyRound } from 'lucide-react';
import { useState, type FormEvent } from 'react';
import { useSearchParams } from 'react-router-dom';
import AuthAlert from '../../components/auth/AuthAlert';
import PasswordField from '../../components/auth/PasswordField';
import PasswordStrength, { passwordChecks } from '../../components/auth/PasswordStrength';
import { Button } from '../../components/ui/Button';
import { useDocumentTitle } from '../../hooks/useDocumentTitle';
import { authApi, QavlioApiError } from '../../services/apiClient';

export default function ResetPasswordPage() {
  const [searchParams] = useSearchParams(); const [identifier, setIdentifier] = useState(searchParams.get('target') || ''); const [tokenOrCode, setTokenOrCode] = useState(searchParams.get('token') || '');
  const [password, setPassword] = useState(''); const [confirmPassword, setConfirmPassword] = useState(''); const [submitting, setSubmitting] = useState(false); const [success, setSuccess] = useState(false); const [error, setError] = useState<string | null>(null);
  useDocumentTitle('Reset password');
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (password !== confirmPassword) { setError('Passwords do not match.'); return; } if (!passwordChecks(password).every((item) => item.passed)) { setError('Create a stronger password before continuing.'); return; } setSubmitting(true); setError(null); try { await authApi.resetPassword({ identifier, tokenOrCode, password, confirmPassword }); setSuccess(true); } catch (requestError) { const code = requestError instanceof QavlioApiError ? requestError.code : ''; setError(code === 'OTP_EXPIRED' ? 'This reset token has expired. Request a new one.' : code === 'OTP_INVALID' || code === 'RESET_INVALID' ? 'This reset token is invalid or has already been used.' : requestError instanceof Error ? requestError.message : 'Password reset failed.'); } finally { setSubmitting(false); } }
  if (success) return <div className="text-center"><span className="mx-auto grid h-16 w-16 place-items-center rounded-2xl bg-emerald-100 text-emerald-700"><CheckCircle2 size={30} /></span><h1 className="mt-5 text-3xl font-extrabold">Password reset successfully</h1><p className="mt-3 text-sm leading-6 text-slate-500">All existing sessions were closed. Sign in again with your new password.</p><Button to="/login" className="mt-7 w-full">Log in</Button></div>;
  return <div><span className="grid h-12 w-12 place-items-center rounded-2xl bg-violet-100 text-violet-700"><KeyRound /></span><h1 className="mt-5 text-3xl font-extrabold">Create a new password</h1><p className="mt-2 text-sm leading-6 text-slate-500">Reset tokens are single-use and expire for your protection.</p>{error && <div className="mt-5"><AuthAlert title={error} /></div>}<form onSubmit={submit} className="mt-6 space-y-4"><label className="block text-xs font-extrabold">Email address<input type="email" className="input-base mt-2" value={identifier} onChange={(event) => setIdentifier(event.target.value)} required /></label><label className="block text-xs font-extrabold">Secure reset token<input className="input-base mt-2" value={tokenOrCode} onChange={(event) => setTokenOrCode(event.target.value)} required /></label><div><PasswordField label="New password" autoComplete="new-password" value={password} onChange={(event) => setPassword(event.target.value)} required /><PasswordStrength password={password} /></div><PasswordField label="Confirm password" autoComplete="new-password" value={confirmPassword} onChange={(event) => setConfirmPassword(event.target.value)} required error={confirmPassword && confirmPassword !== password ? 'Passwords do not match.' : undefined} /><Button type="submit" loading={submitting} className="w-full">Reset password</Button></form></div>;
}
