import React, { useState } from 'react';
import { CheckCircle2, KeyRound } from 'lucide-react';
import { useSearchParams } from 'react-router-dom';
import AuthAlert from '../../components/auth/AuthAlert';
import PasswordStrength from '../../components/auth/PasswordStrength';
import { Button } from '../../components/ui/Button';
import { useDocumentTitle } from '../../hooks/useDocumentTitle';
import { useTranslation } from '../../i18n';
import { authApi } from '../../services/apiClient';

export default function ResetPasswordPage() {
  const [searchParams] = useSearchParams(); const [identifier, setIdentifier] = useState(searchParams.get('target') || ''); const [tokenOrCode, setTokenOrCode] = useState(searchParams.get('token') || ''); const [password, setPassword] = useState(''); const [confirmPassword, setConfirmPassword] = useState(''); const [submitting, setSubmitting] = useState(false); const [success, setSuccess] = useState(false); const [error, setError] = useState(null); const { t } = useTranslation(); useDocumentTitle(t('auth.resetTitle'));
  async function submit(event) { event.preventDefault(); if (password !== confirmPassword) { setError({ message: 'Passwords do not match' }); return; } setSubmitting(true); setError(null); try { await authApi.resetPassword({ identifier, tokenOrCode, password, confirmPassword }); setSuccess(true); } catch (requestError) { setError(requestError); } finally { setSubmitting(false); } }
  if (success) return <div className="text-center"><span className="mx-auto grid h-16 w-16 place-items-center rounded-2xl bg-emerald-100 text-emerald-700"><CheckCircle2 size={30} /></span><h1 className="mt-5 text-3xl font-extrabold">{t('auth.resetSuccess')}</h1><p className="mt-3 text-sm leading-6 text-slate-500">{t('auth.resetSuccessBody')}</p><Button to="/login" className="mt-7 w-full">{t('common.logIn')}</Button></div>;
  return <div><span className="grid h-12 w-12 place-items-center rounded-2xl bg-violet-100 text-violet-700"><KeyRound /></span><h1 className="mt-5 text-3xl font-extrabold">{t('auth.resetTitle')}</h1><p className="mt-2 text-sm leading-6 text-slate-500">{t('auth.resetSubtitle')}</p>{error && <div className="mt-5"><AuthAlert title={error.message} /></div>}<form onSubmit={submit} className="mt-6 space-y-4"><label className="block text-xs font-extrabold" htmlFor="reset-identity">{t('auth.identifier')}<input id="reset-identity" className="input-base mt-2" value={identifier} onChange={(event) => setIdentifier(event.target.value)} required /></label><label className="block text-xs font-extrabold" htmlFor="reset-token">Recovery token or six-digit code<input id="reset-token" className="input-base mt-2" value={tokenOrCode} onChange={(event) => setTokenOrCode(event.target.value)} required /></label><label className="block text-xs font-extrabold" htmlFor="new-password">{t('security.newPassword')}<input id="new-password" type="password" autoComplete="new-password" className="input-base mt-2" value={password} onChange={(event) => setPassword(event.target.value)} required /><PasswordStrength password={password} label={t('auth.passwordHint')} /></label><label className="block text-xs font-extrabold" htmlFor="reset-confirm">{t('common.confirmPassword')}<input id="reset-confirm" type="password" autoComplete="new-password" className="input-base mt-2" value={confirmPassword} onChange={(event) => setConfirmPassword(event.target.value)} required /></label><Button type="submit" disabled={submitting} className="w-full">{submitting ? t('auth.resetting') : t('auth.resetAction')}</Button></form></div>;
}
