import mongoose from 'mongoose';
import { Favorite } from '../models/Favorite.js';
import { Listing } from '../models/Listing.js';
import { AppError } from '../utils/AppError.js';
import { findListingByPublicKey, presentPublicListing } from './listingService.js';
const memory = new Map<string, { userId: string; listingId: string; createdAt: Date }>();
const key = (userId: string, listingId: string) => `${userId}:${listingId}`;
export async function favoriteStatus(userId: string, listingKey: string) { const listing: any = await findListingByPublicKey(listingKey); if (!listing) throw new AppError(404, 'Listing not found', 'LISTING_NOT_FOUND'); const saved = mongoose.connection.readyState === 1 ? Boolean(await Favorite.exists({ userId, listingId: listing._id })) : memory.has(key(userId, listing.publicId)); return { saved }; }
export async function addFavorite(userId: string, listingKey: string) { const listing: any = await findListingByPublicKey(listingKey); if (!listing || !['published','sold'].includes(listing.status)) throw new AppError(404, 'Listing not found', 'LISTING_NOT_FOUND'); if (String(listing.sellerId) === userId) throw new AppError(409, 'You cannot save your own listing', 'OWN_LISTING_FAVORITE'); if (mongoose.connection.readyState === 1) { try { await Favorite.create({ userId, listingId: listing._id }); await Listing.updateOne({ _id: listing._id }, { $inc: { favoriteCount: 1 } }); } catch (error: any) { if (error?.code !== 11000) throw error; } } else if (!memory.has(key(userId, listing.publicId))) memory.set(key(userId, listing.publicId), { userId, listingId: listing.publicId, createdAt: new Date() }); return { saved: true }; }
export async function removeFavorite(userId: string, listingKey: string) { const listing: any = await findListingByPublicKey(listingKey); if (!listing) throw new AppError(404, 'Listing not found', 'LISTING_NOT_FOUND'); if (mongoose.connection.readyState === 1) { const removed = await Favorite.findOneAndDelete({ userId, listingId: listing._id }); if (removed) await Listing.updateOne({ _id: listing._id, favoriteCount: { $gt: 0 } }, { $inc: { favoriteCount: -1 } }); } else memory.delete(key(userId, listing.publicId)); return { saved: false }; }
export async function listFavorites(userId: string) { if (mongoose.connection.readyState === 1) { const favorites = await Favorite.find({ userId }).sort({ createdAt: -1 }).populate('listingId').lean(); return favorites.map((favorite: any) => favorite.listingId).filter(Boolean).map(presentPublicListing); } const ids = [...memory.values()].filter((item) => item.userId === userId).sort((a,b) => +b.createdAt-+a.createdAt).map((item) => item.listingId); return (await Promise.all(ids.map(findListingByPublicKey))).filter(Boolean).map(presentPublicListing); }
