import crypto from 'node:crypto';
import mongoose from 'mongoose';
import { SellerVerification } from '../models/SellerVerification.js';
import { VerificationDocument } from '../models/VerificationDocument.js';
import { getIdentityRepository } from '../repositories/identityRepository.js';
import { getSellerProfileRepository } from '../repositories/sellerProfileRepository.js';
import { AppError } from '../utils/AppError.js';
import { logAdminActivity } from './adminActivityService.js';
import { recordModerationAction } from './trustSafetyService.js';

const memory = new Map<string, any>(); const documents = new Map<string, any>(); const connected=()=>mongoose.connection.readyState===1;
const sellerPresent=(item:any)=>item?{id:String(item._id||item.id),status:item.status,verificationType:item.verificationType,profile:{fullName:item.profile?.fullName||'',contactEmail:item.profile?.contactEmail||'',contactPhone:item.profile?.contactPhone||'',businessName:item.profile?.businessName||''},submittedAt:item.submittedAt,reviewedAt:item.reviewedAt||null,rejectionReason:['Rejected','Needs More Information'].includes(item.status)?item.rejectionReason||'':undefined,expiresAt:item.expiresAt||null,createdAt:item.createdAt,updatedAt:item.updatedAt}:null;
const adminPresent=(item:any)=>({...sellerPresent(item),sellerId:String(item.sellerId),reviewedBy:item.reviewedBy?String(item.reviewedBy):null,rejectionReason:item.rejectionReason||'',notes:item.notes||''});
async function latest(sellerId:string){return connected()?SellerVerification.findOne({sellerId}).sort({createdAt:-1}).select('+notes').lean():[...memory.values()].filter(item=>item.sellerId===sellerId).sort((a,b)=>+b.createdAt-+a.createdAt)[0]||null}
async function expire(item:any){if(item&&item.status==='Verified'&&item.expiresAt&&new Date(item.expiresAt)<=new Date()){if(connected())await SellerVerification.updateOne({_id:item._id},{$set:{status:'Expired'}});else{item.status='Expired';memory.set(item.id,item)}await getSellerProfileRepository().update(String(item.sellerId),{verificationStatus:'not_verified'}).catch(()=>undefined);await getIdentityRepository().updateUser(String(item.sellerId),{'verification.trustedSeller.status':'expired'});item.status='Expired'}return item}
export async function sellerHasApprovedVerification(sellerId:string){const item=await expire(await latest(sellerId));return Boolean(item&&item.status==='Verified'&&(!item.expiresAt||new Date(item.expiresAt)>new Date()))}
export async function sellerVerificationStatus(sellerId:string){const item=await expire(await latest(sellerId));return item?sellerPresent(item):{status:'Not Started',verificationType:null,profile:null,submittedAt:null,reviewedAt:null,expiresAt:null}}
export async function submitSellerVerification(sellerId:string,input:any){const current:any=await expire(await latest(sellerId));if(current&&['Pending','Under Review','Verified'].includes(current.status))throw new AppError(409,'This verification is already active','VERIFICATION_ACTIVE');const user:any=await getIdentityRepository().findUserById(sellerId);if(!user)throw new AppError(404,'Seller not found','SELLER_NOT_FOUND');const now=new Date(),item:any={id:crypto.randomUUID(),sellerId,status:'Pending',verificationType:input.verificationType,profile:{fullName:String(input.fullName).trim(),contactEmail:String(input.contactEmail||user.email||'').trim().toLowerCase(),contactPhone:String(input.contactPhone||user.phone||'').trim(),businessName:input.verificationType==='business'?String(input.businessName||'').trim():''},submittedAt:now,reviewedAt:null,reviewedBy:null,rejectionReason:'',notes:'',expiresAt:null,createdAt:now,updatedAt:now};if(input.verificationType==='business'&&item.profile.businessName.length<2)throw new AppError(422,'Business name is required','BUSINESS_NAME_REQUIRED');const saved:any=connected()?(await SellerVerification.create(item)).toObject():(memory.set(item.id,item),item);await getSellerProfileRepository().update(sellerId,{verificationStatus:'pending'});await getIdentityRepository().updateUser(sellerId,{'verification.trustedSeller.status':'pending'});return sellerPresent(saved)}
export async function adminVerificationQueue(input:any={}){await expireVerified();let rows:any[]=connected()?await SellerVerification.find({...input.status&&{status:input.status}}).sort({submittedAt:1}).limit(1000).select('+notes').lean():[...memory.values()].filter(item=>!input.status||item.status===input.status).sort((a,b)=>+a.submittedAt-+b.submittedAt);const page=Number(input.page)||1,limit=Math.min(100,Number(input.limit)||25),total=rows.length;rows=rows.slice((page-1)*limit,page*limit);return{verifications:rows.map(adminPresent),pagination:{page,limit,total,totalPages:Math.ceil(total/limit)},summary:{pending:[...memoryOr(rows)].filter((item:any)=>item.status==='Pending').length,underReview:[...memoryOr(rows)].filter((item:any)=>item.status==='Under Review').length}}}
function memoryOr(rows:any[]){return connected()?rows:memory.values()}
export async function adminVerificationDetail(id:string){const item:any=connected()&&mongoose.isValidObjectId(id)?await SellerVerification.findById(id).select('+notes').lean():memory.get(id);if(!item)throw new AppError(404,'Verification not found','VERIFICATION_NOT_FOUND');const docs:any[]=connected()?await VerificationDocument.find({verificationId:item._id}).select('type status uploadedAt reviewedAt').lean():[...documents.values()].filter(doc=>doc.verificationId===id);return{...adminPresent(item),documents:docs.map(doc=>({id:String(doc._id||doc.id),type:doc.type,status:doc.status,uploadedAt:doc.uploadedAt,reviewedAt:doc.reviewedAt||null}))}}
export async function reviewSellerVerification(adminId:string,id:string,action:'review'|'approve'|'reject'|'request_information',input:any,req:any){const item:any=connected()&&mongoose.isValidObjectId(id)?await SellerVerification.findById(id).select('+notes').lean():memory.get(id);if(!item)throw new AppError(404,'Verification not found','VERIFICATION_NOT_FOUND');if(['Expired'].includes(item.status))throw new AppError(409,'Expired verification cannot be reviewed','VERIFICATION_STATUS_INVALID');const status=action==='review'?'Under Review':action==='approve'?'Verified':action==='reject'?'Rejected':'Needs More Information';if(['reject','request_information'].includes(action)&&String(input.reason||'').trim().length<5)throw new AppError(422,'A clear review reason is required','VERIFICATION_REASON_REQUIRED');const now=new Date(),patch:any={status,reviewedBy:adminId,reviewedAt:now,rejectionReason:action==='approve'?'':String(input.reason||''),notes:String(input.notes||''),...(action==='approve'&&{expiresAt:new Date(now.getTime()+365*86400000)})};let saved:any;if(connected())saved=await SellerVerification.findByIdAndUpdate(item._id,{$set:patch},{new:true,runValidators:true}).select('+notes').lean();else{saved={...item,...patch,updatedAt:now};memory.set(id,saved)}const publicStatus=status==='Verified'?'verified':status==='Rejected'?'rejected':'pending';await getSellerProfileRepository().update(String(item.sellerId),{verificationStatus:publicStatus});await getIdentityRepository().updateUser(String(item.sellerId),{'verification.trustedSeller.status':publicStatus,'verification.trustedSeller.verifiedAt':status==='Verified'?now:null,'verification.trustedSeller.reason':patch.rejectionReason});await recordModerationAction(adminId,'verification',id,action.toUpperCase(),patch.rejectionReason||'Verification reviewed',req);await logAdminActivity(adminId,`ADMIN_VERIFICATION_${action.toUpperCase()}`,'verification',id,{sellerId:String(item.sellerId),status},req);return adminPresent(saved)}
export async function expireVerified(){const now=new Date();if(connected()){const rows:any[]=await SellerVerification.find({status:'Verified',expiresAt:{$lte:now}}).lean();for(const item of rows)await expire(item)}else for(const item of memory.values())await expire(item)}
export function resetSellerVerificationMemory(){memory.clear();documents.clear()}
