import { AppError } from '../utils/AppError.js';
import { sellerVerificationStatus, submitSellerVerification, adminVerificationQueue, adminVerificationDetail, reviewSellerVerification } from '../services/sellerVerificationService.js';
import { adminAppeals, createRestriction, listMyAppeals, listRestrictions, moderationQueue, moderationRules, recordModerationAction, recordViolation, resolveAppeal, revokeRestriction, safetyAnalytics, saveModerationRule, submitAppeal, violationHistory } from '../services/trustSafetyService.js';
import { reportListing, listMyListingReports } from '../services/reportService.js';
import { reportUser, listMyReports as listMyUserReports } from '../services/userReportService.js';
import { listMyReviewReports, reportReview, adminSetReviewStatus } from '../services/reviewService.js';
import { adminUpdateListingStatus } from '../services/listingService.js';
import { updateAdminReport } from '../services/adminReportService.js';
import { createSystemNotification } from '../services/messagingService.js';

export async function verificationStatus(req,res){res.json({success:true,data:await sellerVerificationStatus(req.auth.userId)})}
export async function verificationSubmit(req,res){res.status(201).json({success:true,data:await submitSellerVerification(req.auth.userId,req.body)})}
export async function verificationDocumentIntent(_req,_res){throw new AppError(503,'Private verification document storage is not configured for this deployment','PRIVATE_STORAGE_UNAVAILABLE')}
export async function verificationQueue(req,res){res.json({success:true,data:await adminVerificationQueue(req.query)})}
export async function verificationDetail(req,res){res.json({success:true,data:await adminVerificationDetail(req.params.id)})}
export async function verificationAction(req,res){res.json({success:true,data:await reviewSellerVerification(req.auth.userId,req.params.id,req.params.action,req.body,req)})}
export async function unifiedReport(req,res){const allowed:any={listing:['scam','fraud','incorrect','misleading','wrong-price','counterfeit','prohibited','duplicate','offensive','wrong-category','other'],seller:['scam','harassment','spam','fake-identity','suspicious','other'],user:['scam','harassment','spam','fake-identity','suspicious','other'],advertisement:['scam','spam','suspicious','other'],review:['spam','fake','fake-review','abuse','harassment','offensive','off-topic','manipulation','other']};if(!allowed[req.body.targetType]?.includes(req.body.reason))throw new AppError(422,'Choose a valid reason for this report target','REPORT_REASON_INVALID');let data;if(req.body.targetType==='listing')data=await reportListing(req.auth.userId,req.body.targetId,{reason:req.body.reason,description:req.body.description});else if(['seller','user','advertisement'].includes(req.body.targetType))data=await reportUser(req.auth.userId,req.body.targetId,{reason:req.body.reason,description:req.body.description,targetType:req.body.targetType});else if(req.body.targetType==='review')data=await reportReview(req.auth.userId,req.body.targetId,{reason:req.body.reason,description:req.body.description});else throw new AppError(422,'Report target is invalid','REPORT_TARGET_INVALID');res.status(201).json({success:true,data,message:'Report submitted for review'})}
export async function myReports(req,res){const[user,listing,review]=await Promise.all([listMyUserReports(req.auth.userId),listMyListingReports(req.auth.userId),listMyReviewReports(req.auth.userId)]);res.json({success:true,data:[...user,...listing,...review].sort((a,b)=>+new Date(b.createdAt)-+new Date(a.createdAt))})}
export async function appealSubmit(req,res){res.status(201).json({success:true,data:await submitAppeal(req.auth.userId,req.body)})}
export async function myAppeals(req,res){res.json({success:true,data:await listMyAppeals(req.auth.userId)})}
export async function appealQueue(req,res){res.json({success:true,data:await adminAppeals(req.query)})}
export async function appealResolve(req,res){res.json({success:true,data:await resolveAppeal(req.auth.userId,req.params.id,req.body,req)})}
export async function restrictions(req,res){res.json({success:true,data:await listRestrictions(req.query)})}
export async function restrictionCreate(req,res){res.status(201).json({success:true,data:await createRestriction(req.auth.userId,req.body,req)})}
export async function restrictionRevoke(req,res){res.json({success:true,data:await revokeRestriction(req.auth.userId,req.params.id,req.body.reason,req)})}
export async function myRestrictions(req,res){res.json({success:true,data:await listRestrictions({userId:req.auth.userId,status:'Active'})})}
export async function moderation(req,res){res.json({success:true,data:await moderationQueue()})}
export async function moderationAction(req,res){const{targetType,action,reason}=req.body;let data:any;if(targetType==='listing'){const status:any={approve:'published',reject:'rejected',request_changes:'pending',suspend:'paused',remove:'removed',restore:'published'}[action];if(!status)throw new AppError(422,'Listing moderation action is invalid','MODERATION_ACTION_INVALID');data=await adminUpdateListingStatus(req.params.id,status,reason,req.auth.userId)}else if(targetType==='report'){const status:any={review:'investigating',resolve:'resolved',dismiss:'rejected',escalate:'escalated'}[action];if(!status)throw new AppError(422,'Report moderation action is invalid','MODERATION_ACTION_INVALID');data=await updateAdminReport(req.auth.userId,req.params.id,status,reason,req)}else if(targetType==='review'){const status:any={approve:'Published',hide:'Hidden',remove:'Removed',restore:'Published'}[action];if(!status)throw new AppError(422,'Review moderation action is invalid','MODERATION_ACTION_INVALID');data=await adminSetReviewStatus(req.params.id,status)}else if(['user','seller'].includes(targetType)){if(action==='warning'){await createSystemNotification(req.params.id,{type:'system',title:'QAVLIO safety warning',body:reason,relatedId:req.params.id,relatedType:'system'});await recordModerationAction(req.auth.userId,targetType,req.params.id,'WARNING',reason,req);await recordViolation(req.auth.userId,req.params.id,'SAFETY_WARNING',req.params.id,'WARNING');data={warned:true}}else{const type:any={restrict_messaging:'MESSAGING',restrict_listing:'LISTING',restrict_selling:'SELLING',suspend:'ACCOUNT'}[action];if(!type)throw new AppError(422,'User moderation action is invalid','MODERATION_ACTION_INVALID');data=await createRestriction(req.auth.userId,{userId:req.params.id,type,reason,startAt:new Date().toISOString(),endAt:req.body.endAt||null},req)}}else throw new AppError(422,'Moderation target is invalid','MODERATION_TARGET_INVALID');res.json({success:true,data})}
export async function rules(req,res){res.json({success:true,data:await moderationRules()})}
export async function ruleCreate(req,res){res.status(201).json({success:true,data:await saveModerationRule(req.auth.userId,undefined,req.body,req)})}
export async function ruleUpdate(req,res){res.json({success:true,data:await saveModerationRule(req.auth.userId,req.params.id,req.body,req)})}
export async function safetyMetrics(_req,res){res.json({success:true,data:await safetyAnalytics()})}
export async function violations(req,res){res.json({success:true,data:await violationHistory(req.params.userId)})}
