import { Router } from 'express';
import { z } from 'zod';
import { ADMIN_PERMISSIONS } from '../constants/adminPermissions.js';
import { ADMIN_ROLE_VALUES } from '../constants/roles.js';
import { aiOverview, aiUpdate, analytics, announcementCreate, announcements, announcementUpdate, auditLogs, commandNotifications, csvExport, order, orders, packageCreate, packages, packageUpdate, promotionAnalytics, sellerFinancials, support, supportCreate, supportDetail, supportReply, supportUpdate, timeline, trustSafety } from '../controllers/adminCommandController.js';
import { requirePermission } from '../middleware/adminPermission.js';
import { authorize } from '../middleware/auth.js';
import { authenticateAdmin } from '../middleware/adminAuth.js';
import { validate } from '../middleware/validate.js';
import { asyncHandler } from '../utils/asyncHandler.js';

const page = z.object({ page: z.coerce.number().int().min(1).default(1), limit: z.coerce.number().int().min(1).max(100).default(25), search: z.string().trim().max(100).optional() });
const packageSchema = z.object({ name: z.string().trim().min(2).max(100), description: z.string().trim().min(5).max(500), price: z.number().min(0).max(10_000_000), currency: z.literal('PKR'), listingCredits: z.number().int().min(0).max(10000), promotionCredits: z.number().int().min(0).max(10000), promotionDays: z.number().int().min(0).max(3650), validityDays: z.number().int().min(1).max(3650), features: z.array(z.string().trim().min(1).max(150)).max(20), active: z.boolean(), sortOrder: z.number().int().min(0).max(1000) }).strict();
const announcement = z.object({ title: z.string().trim().min(3).max(140), message: z.string().trim().min(5).max(1200), type: z.enum(['Info','Warning','Update','Maintenance']), audience: z.enum(['all','buyers','sellers','verified_sellers']), status: z.enum(['Draft','Scheduled','Active','Cancelled']), startAt: z.string().datetime(), endAt: z.string().datetime() }).strict();

export const adminCommandRouter = Router();
adminCommandRouter.use(asyncHandler(authenticateAdmin), authorize(...ADMIN_ROLE_VALUES));
adminCommandRouter.get('/orders', requirePermission(ADMIN_PERMISSIONS.ORDERS_VIEW), validate(page.extend({ status: z.enum(['Created','Pending','Processing','Paid','Failed','Cancelled','Refunded']).optional(), type: z.enum(['LISTING_FEE','PROMOTION','PACKAGE']).optional(), userId: z.string().max(100).optional(), sort: z.enum(['newest','oldest']).default('newest') }), 'query'), asyncHandler(orders));
adminCommandRouter.get('/orders/:id', requirePermission(ADMIN_PERMISSIONS.ORDERS_VIEW), asyncHandler(order));
adminCommandRouter.get('/analytics/command-center', requirePermission(ADMIN_PERMISSIONS.ANALYTICS_VIEW), validate(z.object({ days: z.coerce.number().int().min(1).max(365).default(30) }), 'query'), asyncHandler(analytics));
adminCommandRouter.get('/trust-safety', requirePermission(ADMIN_PERMISSIONS.TRUST_SAFETY_VIEW), asyncHandler(trustSafety));
adminCommandRouter.get('/notifications', requirePermission(ADMIN_PERMISSIONS.DASHBOARD_VIEW), asyncHandler(commandNotifications));
adminCommandRouter.post('/notifications', requirePermission(ADMIN_PERMISSIONS.ANNOUNCEMENTS_MANAGE), validate(announcement), asyncHandler(announcementCreate));
adminCommandRouter.patch('/notifications/:id', requirePermission(ADMIN_PERMISSIONS.ANNOUNCEMENTS_MANAGE), validate(announcement.partial().strict()), asyncHandler(announcementUpdate));
adminCommandRouter.get('/promotions/analytics', requirePermission(ADMIN_PERMISSIONS.FINANCE_VIEW), asyncHandler(promotionAnalytics));
adminCommandRouter.get('/sellers/:id/financials', requirePermission(ADMIN_PERMISSIONS.FINANCE_VIEW), asyncHandler(sellerFinancials));
adminCommandRouter.get('/support', requirePermission(ADMIN_PERMISSIONS.SUPPORT_VIEW), validate(page.extend({ status: z.enum(['Open','In Progress','Waiting for User','Resolved','Closed']).optional(), priority: z.enum(['low','medium','high','urgent']).optional(), assignedTo: z.string().max(100).optional() }), 'query'), asyncHandler(support));
adminCommandRouter.post('/support', requirePermission(ADMIN_PERMISSIONS.SUPPORT_MANAGE), validate(z.object({ userId: z.string().min(3).max(100), subject: z.string().trim().min(3).max(160), category: z.enum(['payment','listing','account','chat','safety','other']), description: z.string().trim().min(8).max(4000), priority: z.enum(['low','medium','high','urgent']).default('medium') }).strict()), asyncHandler(supportCreate));
adminCommandRouter.get('/support/:id', requirePermission(ADMIN_PERMISSIONS.SUPPORT_VIEW), asyncHandler(supportDetail));
adminCommandRouter.patch('/support/:id', requirePermission(ADMIN_PERMISSIONS.SUPPORT_MANAGE), validate(z.object({ status: z.enum(['Open','In Progress','Waiting for User','Resolved','Closed']).optional(), assignedTo: z.string().max(100).nullable().optional(), priority: z.enum(['low','medium','high','urgent']).optional() }).strict().refine((value) => Object.keys(value).length > 0)), asyncHandler(supportUpdate));
adminCommandRouter.post('/support/:id/replies', requirePermission(ADMIN_PERMISSIONS.SUPPORT_MANAGE), validate(z.object({ body: z.string().trim().min(2).max(4000), internal: z.boolean().default(false) }).strict()), asyncHandler(supportReply));
adminCommandRouter.get('/announcements', requirePermission(ADMIN_PERMISSIONS.ANNOUNCEMENTS_VIEW), validate(z.object({ status: z.enum(['Draft','Scheduled','Active','Expired','Cancelled']).optional(), audience: z.enum(['all','buyers','sellers','verified_sellers']).optional() }), 'query'), asyncHandler(announcements));
adminCommandRouter.post('/announcements', requirePermission(ADMIN_PERMISSIONS.ANNOUNCEMENTS_MANAGE), validate(announcement), asyncHandler(announcementCreate));
adminCommandRouter.patch('/announcements/:id', requirePermission(ADMIN_PERMISSIONS.ANNOUNCEMENTS_MANAGE), validate(announcement.partial().strict()), asyncHandler(announcementUpdate));
adminCommandRouter.get('/audit-logs', requirePermission(ADMIN_PERMISSIONS.ACTIVITY_VIEW), validate(page.extend({ admin: z.string().max(100).optional(), action: z.string().max(100).optional(), targetType: z.string().max(80).optional(), result: z.enum(['success','denied','failed']).optional(), date: z.string().datetime().optional() }), 'query'), asyncHandler(auditLogs));
adminCommandRouter.get('/activity/:type/:id', requirePermission(ADMIN_PERMISSIONS.ACTIVITY_VIEW), validate(z.object({ limit: z.coerce.number().int().min(1).max(100).default(30) }), 'query'), asyncHandler(timeline));
adminCommandRouter.get('/ai', requirePermission(ADMIN_PERMISSIONS.AI_VIEW), validate(z.object({ days: z.coerce.number().int().min(1).max(365).default(30) }), 'query'), asyncHandler(aiOverview));
adminCommandRouter.patch('/ai', requirePermission(ADMIN_PERMISSIONS.AI_MANAGE), validate(z.object({ enabled: z.boolean().optional(), provider: z.enum(['heuristic','openai','gemini']).optional(), model: z.string().max(80).optional(), requestLimitPerMinute: z.number().int().min(1).max(120).optional(), requestLimitPerDay: z.number().int().min(1).max(5000).optional(), features: z.object({ assistant: z.boolean().optional(), search: z.boolean().optional(), recommendations: z.boolean().optional(), listingAssistant: z.boolean().optional(), support: z.boolean().optional(), moderation: z.boolean().optional() }).optional() }).strict()), asyncHandler(aiUpdate));
adminCommandRouter.get('/packages', requirePermission(ADMIN_PERMISSIONS.ORDERS_VIEW), asyncHandler(packages));
adminCommandRouter.post('/packages', requirePermission(ADMIN_PERMISSIONS.PACKAGES_MANAGE), validate(packageSchema), asyncHandler(packageCreate));
adminCommandRouter.patch('/packages/:id', requirePermission(ADMIN_PERMISSIONS.PACKAGES_MANAGE), validate(packageSchema.partial().strict()), asyncHandler(packageUpdate));
adminCommandRouter.get('/exports/:dataset', requirePermission(ADMIN_PERMISSIONS.EXPORT_DATA), validate(z.object({ dataset: z.enum(['users','listings','orders','payments','reports']) }), 'params'), asyncHandler(csvExport));
