import { Router } from 'express'; import { z } from 'zod';
import { archive, block, index, messages, read, report, send, show, uploadIntent } from '../controllers/messageController.js';
import { authenticate } from '../middleware/auth.js'; import { conversationRateLimit, mediaIntentRateLimit, messageRateLimit, reportRateLimit } from '../middleware/authRateLimits.js'; import { validate } from '../middleware/validate.js'; import { asyncHandler } from '../utils/asyncHandler.js';
const attachment=z.object({url:z.string().url().max(1000),thumbnailUrl:z.string().url().max(1000).optional(),key:z.string().trim().min(3).max(300),width:z.number().int().positive().max(10000).optional(),height:z.number().int().positive().max(10000).optional(),mimeType:z.enum(['image/jpeg','image/png','image/webp'])}).strict();
const message=z.object({text:z.string().trim().max(5000).optional().default(''),attachments:z.array(attachment).max(5).optional().default([]),clientId:z.string().uuid()}).strict().refine((value)=>value.text.length>0||value.attachments.length>0,{message:'Write a message or add an image'});
const query=z.object({q:z.string().trim().max(100).optional(),archived:z.coerce.boolean().default(false),page:z.coerce.number().int().min(1).default(1),limit:z.coerce.number().int().min(1).max(50).default(30)});
const messageQuery=z.object({before:z.string().max(100).optional(),limit:z.coerce.number().int().min(1).max(100).default(40)});
export const conversationRouter=Router();conversationRouter.use(asyncHandler(authenticate));
conversationRouter.get('/',validate(query,'query'),asyncHandler(index));conversationRouter.get('/:id',asyncHandler(show));conversationRouter.get('/:id/messages',validate(messageQuery,'query'),asyncHandler(messages));conversationRouter.post('/:id/messages',messageRateLimit,validate(message),asyncHandler(send));conversationRouter.post('/:id/read',asyncHandler(read));conversationRouter.post('/:id/archive',conversationRateLimit,validate(z.object({archived:z.boolean().default(true)})),asyncHandler(archive));conversationRouter.post('/:id/block',conversationRateLimit,validate(z.object({blocked:z.boolean()})),asyncHandler(block));conversationRouter.post('/:id/report',reportRateLimit,validate(z.object({reason:z.enum(['scam','harassment','spam','prohibited','suspicious','other']),description:z.string().trim().max(1000).optional().default('')})),asyncHandler(report));conversationRouter.post('/attachments/intent',mediaIntentRateLimit,validate(z.object({fileName:z.string().trim().min(1).max(200),fileType:z.enum(['image/jpeg','image/png','image/webp']),fileSize:z.number().int().positive().max(5*1024*1024)})),asyncHandler(uploadIntent));
