import { Router } from 'express';
import { accountLinkRouter } from './accountLinkRoutes.js';
import { adRouter } from './adRoutes.js';
import { adminUserRouter } from './adminUserRoutes.js';
import { authRouter } from './authRoutes.js';
import { categoryRouter } from './categoryRoutes.js';
import { configRouter } from './configRoutes.js';
import { userRouter } from './userRoutes.js';
import { sellerRouter } from './sellerRoutes.js';
import { searchRouter } from './searchRoutes.js';
import { listingRouter } from './listingRoutes.js';
import { sellerListingRouter } from './sellerListingRoutes.js';
import { conversationRouter } from './conversationRoutes.js';
import { notificationRouter } from './notificationRoutes.js';
import { paymentRouter } from './paymentRoutes.js';
import { promotionRouter } from './promotionRoutes.js';
import { adminAdRouter } from './adminAdRoutes.js';
import { adminControlRouter } from './adminControlRoutes.js';
import { aiRouter } from './aiRoutes.js';
import { recommendationRouter } from './recommendationRoutes.js';
import { reviewRouter } from './reviewRoutes.js';
import { safetyRouter } from './safetyRoutes.js';
import { favoriteRouter } from './favoriteRoutes.js';
import { savedSearchRouter } from './savedSearchRoutes.js';
import { followRouter } from './followRoutes.js';
import { recentSearchRouter } from './recentSearchRoutes.js';
import { recentlyViewedRouter } from './recentlyViewedRoutes.js';
import { locationRouter } from './locationRoutes.js';
import { discoveryRouter } from './discoveryRoutes.js';
import { monetizationRouter } from './monetizationRoutes.js';
import { adminMonetizationRouter } from './adminMonetizationRoutes.js';
import { analyticsRouter } from './analyticsRoutes.js';
import { adminCommandRouter } from './adminCommandRoutes.js';
import { adminTrustSafetyRouter, trustSafetyRouter } from './trustSafetyRoutes.js';
import { notificationPreferences, patchNotificationPreferences } from '../controllers/userController.js';
import { authenticate } from '../middleware/auth.js';
import { validate } from '../middleware/validate.js';
import { asyncHandler } from '../utils/asyncHandler.js';
import { z } from 'zod';
import { index as followingIndex } from '../controllers/followController.js';
import { blockedListings, blocks as blockedUsers } from '../controllers/blockController.js';

export const apiRouter = Router();
apiRouter.use('/auth', authRouter);
apiRouter.use('/users', userRouter);
apiRouter.use('/sellers', sellerRouter);
apiRouter.use('/seller', sellerListingRouter);
apiRouter.use('/listings', listingRouter);
apiRouter.use('/conversations', conversationRouter);
apiRouter.use('/notifications', notificationRouter);
apiRouter.use('/payments', paymentRouter);
apiRouter.use('/promotions', promotionRouter);
apiRouter.use('/monetization', monetizationRouter);
apiRouter.use('/analytics', analyticsRouter);
apiRouter.use('/account-links', accountLinkRouter);
apiRouter.use('/admin', adminTrustSafetyRouter);
apiRouter.use('/admin', adminCommandRouter);
apiRouter.use('/admin/users', adminUserRouter);
apiRouter.use('/admin', adminMonetizationRouter);
apiRouter.use('/admin', adminControlRouter);
apiRouter.use('/admin/ads', adminAdRouter);
apiRouter.use('/categories', categoryRouter);
apiRouter.use('/search', searchRouter);
apiRouter.use('/config', configRouter);
apiRouter.use('/ads', adRouter);
apiRouter.use('/ai', aiRouter);
apiRouter.use('/recommendations', recommendationRouter);
apiRouter.use('/reviews', reviewRouter);
apiRouter.use('/safety', safetyRouter);
apiRouter.use('/favorites', favoriteRouter);
apiRouter.use('/saved-searches', savedSearchRouter);
apiRouter.use('/follows', followRouter);
apiRouter.get('/following', asyncHandler(authenticate), asyncHandler(followingIndex));
apiRouter.get('/blocked-users', asyncHandler(authenticate), asyncHandler(blockedUsers));
apiRouter.get('/blocked-listings', asyncHandler(authenticate), asyncHandler(blockedListings));
apiRouter.use('/recent-searches', recentSearchRouter);
apiRouter.use('/recently-viewed', recentlyViewedRouter);
apiRouter.use('/locations', locationRouter);
apiRouter.use('/discovery', discoveryRouter);
apiRouter.use('/', trustSafetyRouter);
apiRouter.get('/notification-preferences', asyncHandler(authenticate), asyncHandler(notificationPreferences));
apiRouter.patch('/notification-preferences', asyncHandler(authenticate), validate(z.object({
  inApp: z.boolean().optional(), email: z.boolean().optional(), push: z.boolean().optional(), sms: z.boolean().optional(), security: z.boolean().optional(), marketing: z.boolean().optional(),
  messages: z.boolean().optional(), listingUpdates: z.boolean().optional(), account: z.boolean().optional(), promotions: z.boolean().optional(), announcements: z.boolean().optional(),
  savedSearchAlerts: z.boolean().optional(), priceAlerts: z.boolean().optional(), sellerUpdates: z.boolean().optional(), listingAvailability: z.boolean().optional(), payments: z.boolean().optional(),
})), asyncHandler(patchNotificationPreferences));
