import { Router } from 'express';
import { z } from 'zod';
import { create, patch, related, remove, show, transition, uploadIntent, view } from '../controllers/listingController.js';
import { add as addFavorite, remove as removeFavorite, status as favoriteStatus } from '../controllers/favoriteController.js';
import { create as createReport } from '../controllers/reportController.js';
import { create as createConversation } from '../controllers/conversationController.js';
import { USER_ROLES } from '../constants/roles.js';
import { authenticate, authorize } from '../middleware/auth.js';
import { optionalAuthenticate } from '../middleware/optionalAuth.js';
import { validate } from '../middleware/validate.js';
import { conversationRateLimit } from '../middleware/authRateLimits.js';
import { listingInputSchema } from '../validators/listingValidator.js';
import { asyncHandler } from '../utils/asyncHandler.js';
const imageIntent = z.object({ fileName: z.string().trim().min(1).max(200), fileType: z.enum(['image/jpeg', 'image/png', 'image/webp']), fileSize: z.number().int().positive().max(8 * 1024 * 1024) }).strict();
const reportInput = z.object({ reason: z.enum(['scam','incorrect','prohibited','duplicate','offensive','wrong-category','other']), description: z.string().trim().max(1000).optional().default('') }).strict();
export const listingRouter = Router();
listingRouter.get('/:id/related', asyncHandler(related));
listingRouter.get('/:id', optionalAuthenticate, asyncHandler(show));
listingRouter.post('/:id/view', optionalAuthenticate, asyncHandler(view));
listingRouter.use(asyncHandler(authenticate));
listingRouter.get('/:id/favorite', asyncHandler(favoriteStatus));
listingRouter.post('/:id/favorite', asyncHandler(addFavorite));
listingRouter.delete('/:id/favorite', asyncHandler(removeFavorite));
listingRouter.post('/:id/report', validate(reportInput), asyncHandler(createReport));
listingRouter.post('/:id/conversation', conversationRateLimit, asyncHandler(createConversation));
listingRouter.use(authorize(USER_ROLES.SELLER));
listingRouter.post('/uploads/intent', validate(imageIntent), asyncHandler(uploadIntent));
listingRouter.post('/', validate(listingInputSchema), asyncHandler(create));
listingRouter.patch('/:id', validate(listingInputSchema.partial()), asyncHandler(patch));
listingRouter.delete('/:id', asyncHandler(remove));
for (const action of ['publish', 'pause', 'resume', 'sold']) listingRouter.post(`/:id/${action}`, (req, _res, next) => { (req.params as any).action = action; next(); }, asyncHandler(transition));
