import { Router } from 'express';
import { z } from 'zod';
import { ADMIN_PERMISSIONS } from '../constants/adminPermissions.js';
import { ADMIN_ROLE_VALUES, USER_ROLES } from '../constants/roles.js';
import { appealQueue, appealResolve, appealSubmit, myAppeals, myReports, myRestrictions, moderation, moderationAction, restrictionCreate, restrictionRevoke, restrictions, ruleCreate, rules, ruleUpdate, safetyMetrics, unifiedReport, verificationAction, verificationDetail, verificationDocumentIntent, verificationQueue, verificationStatus, verificationSubmit, violations } from '../controllers/trustSafetyController.js';
import { requirePermission } from '../middleware/adminPermission.js';
import { authenticate, authorize } from '../middleware/auth.js';
import { appealRateLimit, mediaIntentRateLimit, moderationActionRateLimit, reportRateLimit, verificationSubmissionRateLimit } from '../middleware/authRateLimits.js';
import { validate } from '../middleware/validate.js';
import { asyncHandler } from '../utils/asyncHandler.js';

export const trustSafetyRouter=Router();
trustSafetyRouter.use((req,res,next)=>['/verification','/reports','/appeals','/restrictions'].some(prefix=>req.path.startsWith(prefix))?asyncHandler(authenticate)(req,res,next):next());
trustSafetyRouter.get('/verification/status',authorize(USER_ROLES.SELLER),asyncHandler(verificationStatus));
trustSafetyRouter.post('/verification/submit',authorize(USER_ROLES.SELLER),verificationSubmissionRateLimit,validate(z.object({verificationType:z.enum(['individual','business']),fullName:z.string().trim().min(2).max(120),contactEmail:z.string().email().max(200).optional().default(''),contactPhone:z.string().trim().max(30).optional().default(''),businessName:z.string().trim().max(160).optional().default('')}).strict()),asyncHandler(verificationSubmit));
trustSafetyRouter.post('/verification/documents/intent',authorize(USER_ROLES.SELLER),mediaIntentRateLimit,validate(z.object({type:z.enum(['identity_front','identity_back','business_registration','address_evidence','other']),fileName:z.string().trim().min(1).max(180),fileType:z.enum(['image/jpeg','image/png','application/pdf']),fileSize:z.number().int().positive().max(8*1024*1024)}).strict()),asyncHandler(verificationDocumentIntent));
trustSafetyRouter.post('/reports',reportRateLimit,validate(z.object({targetType:z.enum(['listing','seller','user','advertisement','review']),targetId:z.string().min(3).max(120),reason:z.enum(['scam','fraud','incorrect','misleading','wrong-price','counterfeit','prohibited','duplicate','offensive','wrong-category','harassment','spam','fake-identity','suspicious','fake','fake-review','abuse','off-topic','manipulation','other']),description:z.string().trim().max(1000).optional().default('')}).strict()),asyncHandler(unifiedReport));
trustSafetyRouter.get('/reports',asyncHandler(myReports));
trustSafetyRouter.post('/appeals',appealRateLimit,validate(z.object({targetType:z.enum(['listing','account','restriction','verification']),targetId:z.string().min(3).max(120),reason:z.string().trim().min(3).max(120),description:z.string().trim().min(20).max(3000),evidenceReferences:z.array(z.string().regex(/^evidence_[a-zA-Z0-9_-]{8,100}$/)).max(5).optional().default([])}).strict()),asyncHandler(appealSubmit));
trustSafetyRouter.get('/appeals',asyncHandler(myAppeals));
trustSafetyRouter.get('/restrictions/me',asyncHandler(myRestrictions));

export const adminTrustSafetyRouter=Router();
adminTrustSafetyRouter.use(asyncHandler(authenticate),authorize(...ADMIN_ROLE_VALUES));
adminTrustSafetyRouter.get('/verification',requirePermission(ADMIN_PERMISSIONS.VERIFICATION_VIEW),validate(z.object({status:z.enum(['Pending','Under Review','Verified','Rejected','Needs More Information','Expired']).optional(),page:z.coerce.number().int().min(1).default(1),limit:z.coerce.number().int().min(1).max(100).default(25)}),'query'),asyncHandler(verificationQueue));
adminTrustSafetyRouter.get('/verification/:id',requirePermission(ADMIN_PERMISSIONS.VERIFICATION_VIEW),asyncHandler(verificationDetail));
for(const action of ['review','approve','reject','request_information'] as const)adminTrustSafetyRouter.post(`/verification/:id/${action}`,requirePermission(ADMIN_PERMISSIONS.VERIFICATION_MANAGE),moderationActionRateLimit,validate(z.object({reason:z.string().trim().max(1000).optional().default(''),notes:z.string().trim().max(2000).optional().default('')}).strict()),(req,_res,next)=>{req.params.action=action;next()},asyncHandler(verificationAction));
adminTrustSafetyRouter.get('/appeals',requirePermission(ADMIN_PERMISSIONS.APPEALS_VIEW),validate(z.object({status:z.enum(['Pending','Under Review','Needs Information','Accepted','Rejected']).optional(),page:z.coerce.number().int().min(1).default(1),limit:z.coerce.number().int().min(1).max(100).default(25)}),'query'),asyncHandler(appealQueue));
adminTrustSafetyRouter.post('/appeals/:id/resolve',requirePermission(ADMIN_PERMISSIONS.APPEALS_MANAGE),moderationActionRateLimit,validate(z.object({action:z.enum(['review','accept','reject','request_information']),note:z.string().trim().min(3).max(2000)}).strict()),asyncHandler(appealResolve));
adminTrustSafetyRouter.get('/restrictions',requirePermission(ADMIN_PERMISSIONS.TRUST_SAFETY_VIEW),validate(z.object({userId:z.string().max(120).optional(),status:z.enum(['Active','Expired','Revoked']).optional()}),'query'),asyncHandler(restrictions));
adminTrustSafetyRouter.post('/restrictions',requirePermission(ADMIN_PERMISSIONS.RESTRICTIONS_MANAGE),moderationActionRateLimit,validate(z.object({userId:z.string().min(3).max(120),type:z.enum(['LISTING','MESSAGING','ACCOUNT','SELLING']),reason:z.string().trim().min(5).max(1000),startAt:z.string().datetime().optional(),endAt:z.string().datetime().nullable().optional()}).strict()),asyncHandler(restrictionCreate));
adminTrustSafetyRouter.post('/restrictions/:id/revoke',requirePermission(ADMIN_PERMISSIONS.RESTRICTIONS_MANAGE),moderationActionRateLimit,validate(z.object({reason:z.string().trim().min(3).max(1000)}).strict()),asyncHandler(restrictionRevoke));
adminTrustSafetyRouter.get('/moderation',requirePermission(ADMIN_PERMISSIONS.TRUST_SAFETY_VIEW),asyncHandler(moderation));
adminTrustSafetyRouter.post('/moderation/:id/action',requirePermission(ADMIN_PERMISSIONS.LISTINGS_MODERATE),moderationActionRateLimit,validate(z.object({targetType:z.enum(['listing','user','seller','report','review']),action:z.enum(['approve','reject','request_changes','suspend','remove','restore','review','resolve','dismiss','escalate','hide','warning','restrict_messaging','restrict_listing','restrict_selling']),reason:z.string().trim().min(3).max(2000),endAt:z.string().datetime().nullable().optional()}).strict()),asyncHandler(moderationAction));
adminTrustSafetyRouter.get('/moderation/rules',requirePermission(ADMIN_PERMISSIONS.TRUST_SAFETY_VIEW),asyncHandler(rules));
const rule=z.object({name:z.string().trim().min(3).max(120),categorySlug:z.string().regex(/^[a-z0-9-]*$/).max(80).optional().default(''),ruleType:z.enum(['PROHIBITED_KEYWORD','CATEGORY_REVIEW','LINK_SPAM','PRICE_ANOMALY','IMAGE_DUPLICATE']),enabled:z.boolean(),severity:z.enum(['LOW','MEDIUM','HIGH','CRITICAL']),action:z.enum(['FLAG','REVIEW','BLOCK']),configuration:z.record(z.union([z.string(),z.number(),z.boolean(),z.array(z.string().max(100)).max(50)])).optional().default({})}).strict();
adminTrustSafetyRouter.post('/moderation/rules',requirePermission(ADMIN_PERMISSIONS.MODERATION_RULES_MANAGE),validate(rule),asyncHandler(ruleCreate));
adminTrustSafetyRouter.patch('/moderation/rules/:id',requirePermission(ADMIN_PERMISSIONS.MODERATION_RULES_MANAGE),validate(rule.partial().strict()),asyncHandler(ruleUpdate));
adminTrustSafetyRouter.get('/trust-safety/analytics',requirePermission(ADMIN_PERMISSIONS.TRUST_SAFETY_VIEW),asyncHandler(safetyMetrics));
adminTrustSafetyRouter.get('/violations/:userId',requirePermission(ADMIN_PERMISSIONS.TRUST_SAFETY_VIEW),asyncHandler(violations));
