import { Router } from 'express';
import { z } from 'zod';
import { deleteMe, me, patchMe, patchNotificationPreferences, patchPassword, removeAllSessions, removePhone, removeSession, sellerOnboarding, sendEmailVerification, sendPhoneVerification, sessions, verificationStatus } from '../controllers/userController.js';
import { authenticate } from '../middleware/auth.js';
import { otpRateLimit } from '../middleware/authRateLimits.js';
import { validate } from '../middleware/validate.js';
import { asyncHandler } from '../utils/asyncHandler.js';

export const userRouter = Router();
userRouter.use(asyncHandler(authenticate));
userRouter.get('/me', asyncHandler(me));
userRouter.patch('/me', validate(z.object({ name: z.string().min(2).max(100).optional(), username: z.string().regex(/^[a-z0-9._]{3,40}$/).optional(), about: z.string().max(1000).optional(), language: z.enum(['en', 'ur']).optional(), location: z.object({ country: z.string().length(2).optional(), province: z.string().max(80).optional(), city: z.string().max(80).optional(), area: z.string().max(100).optional() }).optional() })), asyncHandler(patchMe));
userRouter.patch('/me/password', validate(z.object({ currentPassword: z.string().min(1), password: z.string().min(10).max(128), confirmPassword: z.string() }).refine((value) => value.password === value.confirmPassword, { path: ['confirmPassword'], message: 'Passwords do not match' })), asyncHandler(patchPassword));
userRouter.delete('/me', validate(z.object({ password: z.string().min(1), confirmation: z.literal('DELETE') })), asyncHandler(deleteMe));
userRouter.get('/verification/status', asyncHandler(verificationStatus));
userRouter.post('/verification/phone', otpRateLimit, validate(z.object({ phone: z.string().min(8).max(30) })), asyncHandler(sendPhoneVerification));
userRouter.post('/verification/email', otpRateLimit, validate(z.object({ email: z.string().min(3).max(200) })), asyncHandler(sendEmailVerification));
userRouter.delete('/verification/phone', validate(z.object({ password: z.string().min(1).max(128) })), asyncHandler(removePhone));
userRouter.patch('/me/seller-onboarding', validate(z.object({ accountType: z.enum(['individual', 'business']), businessName: z.string().max(120).optional().default(''), acceptSellerPolicy: z.literal(true) })), asyncHandler(sellerOnboarding));
userRouter.get('/sessions', asyncHandler(sessions));
userRouter.delete('/sessions/all', asyncHandler(removeAllSessions));
userRouter.delete('/sessions/:id', asyncHandler(removeSession));
userRouter.patch('/notification-preferences', validate(z.object({ inApp: z.boolean().optional(), email: z.boolean().optional(), push: z.boolean().optional(), sms: z.boolean().optional(), security: z.boolean().optional(), marketing: z.boolean().optional() })), asyncHandler(patchNotificationPreferences));
