import React from 'react';
import { Bell, ChevronRight, Globe2, KeyRound, LayoutDashboard, LogOut, ShieldCheck, UserRound } from 'lucide-react';
import { NavLink, Outlet } from 'react-router-dom';
import { useAuth } from '../auth/AuthProvider';
import Logo from '../components/ui/Logo';
import { useTranslation } from '../i18n';

export default function AccountLayout() {
  const { user, logout } = useAuth(); const { locale, setLocale } = useTranslation();
  const links = [{ to: '/account/profile', label: 'Profile', icon: UserRound }, { to: '/account/verification', label: 'Trust & verification', icon: ShieldCheck }, { to: '/account/security', label: 'Security & sessions', icon: KeyRound }, { to: '/account/notifications', label: 'Notifications', icon: Bell }, { to: '/account/settings', label: 'Preferences', icon: Globe2 }];
  return <div className="min-h-screen bg-surface"><header className="border-b border-ink-900/10 bg-white"><div className="container-shell flex h-[72px] items-center gap-4"><Logo /><NavLink to="/dashboard" className="ml-auto hidden items-center gap-2 text-xs font-bold text-slate-500 hover:text-violet-700 sm:flex"><LayoutDashboard size={16} /> Dashboard</NavLink><button onClick={logout} className="inline-flex items-center gap-2 rounded-lg px-3 py-2 text-xs font-bold text-slate-500 hover:bg-slate-100"><LogOut size={16} /><span className="hidden sm:inline">Log out</span></button></div></header><div className="container-shell grid gap-6 py-7 lg:grid-cols-[250px_1fr]"><aside><section className="rounded-2xl bg-ink-950 p-4 text-white"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-violet-600 text-xs font-extrabold">{user?.name?.split(' ').map((part) => part[0]).slice(0,2).join('')}</span><div className="min-w-0"><p className="truncate text-xs font-extrabold">{user?.name}</p><p className="mt-1 truncate text-[9px] font-semibold text-white/45">@{user?.username}</p></div></div></section><nav className="hide-scrollbar mt-3 flex gap-2 overflow-x-auto pb-2 lg:block lg:space-y-1" aria-label="Account settings">{links.map(({ to,label,icon: Icon }) => <NavLink key={to} to={to} className={({ isActive }) => `flex shrink-0 items-center gap-2.5 rounded-xl px-3 py-2.5 text-xs font-bold ${isActive ? 'bg-violet-600 text-white shadow-md' : 'bg-white text-slate-600 hover:bg-violet-50 hover:text-violet-700'}`}><Icon size={16} />{label}<ChevronRight size={13} className="ml-auto hidden lg:block" /></NavLink>)}</nav><button onClick={() => setLocale(locale === 'en' ? 'ur' : 'en')} className="mt-3 flex w-full items-center justify-between rounded-xl border border-slate-200 bg-white p-3 text-xs font-bold text-slate-600"><span className="inline-flex items-center gap-2"><Globe2 size={16} /> Language</span><span className="text-violet-700">{locale === 'en' ? 'اردو' : 'English'}</span></button></aside><main className="min-w-0"><Outlet /></main></div></div>;
}
