import React from 'react';
import { BadgeCheck, MapPin, MessageCircle, Mic, Phone, ShieldCheck } from 'lucide-react';
import { Link, useSearchParams } from 'react-router-dom';
import { useAuth } from '../auth/AuthProvider';
import { Button } from '../components/ui/Button';
import { useDocumentTitle } from '../hooks/useDocumentTitle';

const capabilities = [{ icon: BadgeCheck, title: 'Presence and read status', body: 'Authenticated presence, last-seen privacy, delivery, and read receipts.' }, { icon: Mic, title: 'Rich messages', body: 'Voice messages and carefully validated image attachments.' }, { icon: MapPin, title: 'Safer meeting points', body: 'Consent-based approximate location sharing inside a conversation.' }, { icon: ShieldCheck, title: 'Block and report', body: 'Conversation-level blocking, reporting, evidence retention, and moderation.' }];

export default function MessagesPage() {
  const { user } = useAuth(); const [searchParams] = useSearchParams(); const listingId = searchParams.get('listing'); useDocumentTitle('Messages');
  return <div className="container-shell py-10"><div className="mx-auto max-w-4xl"><div className="text-center"><span className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-violet-100 text-violet-700"><MessageCircle size={25} /></span><p className="eyebrow mt-5">Protected conversation space</p><h1 className="mt-2 text-3xl font-extrabold">My chats</h1><p className="mx-auto mt-3 max-w-xl text-sm leading-6 text-slate-500">You are signed in as {user.name}. Durable real-time conversations will arrive in the dedicated messaging phase.</p></div>{listingId && <div className="mx-auto mt-6 max-w-xl rounded-xl border border-violet-200 bg-violet-50 p-4 text-center text-xs font-semibold text-violet-800">Your intent to contact the seller of listing <strong>{listingId}</strong> was preserved after authentication. No message has been sent yet.</div>}<div className="mt-8 grid gap-4 sm:grid-cols-2">{capabilities.map(({ icon: Icon,title,body }) => <article key={title} className="rounded-2xl border border-ink-900/10 bg-white p-5 shadow-sm"><span className="grid h-10 w-10 place-items-center rounded-xl bg-violet-50 text-violet-700"><Icon size={18} /></span><h2 className="mt-4 text-sm font-extrabold">{title}</h2><p className="mt-2 text-xs leading-5 text-slate-500">{body}</p></article>)}</div><section className="mt-5 rounded-2xl bg-ink-950 p-6 text-white"><div className="flex flex-col items-start justify-between gap-5 sm:flex-row sm:items-center"><div><p className="text-xs font-extrabold text-gold-300">HONEST PHASE BOUNDARY</p><h2 className="mt-2 text-lg font-extrabold">No fabricated conversations or messages</h2><p className="mt-2 max-w-xl text-xs leading-5 text-white/55">Phase 2 provides identity, sessions, protected routing, and the user model required by chat. Socket.io rooms, message persistence, voice/media, contact reveal, and moderation come later.</p></div><div className="flex gap-2"><Button to="/browse" variant="gold">Browse listings</Button><Link to="/account/security" className="grid h-11 w-11 place-items-center rounded-xl bg-white/10" aria-label="Account security"><Phone size={17} /></Link></div></div></section></div></div>;
}
