import React, { useState } from 'react';
import { Bell, CheckCircle2, Mail, MessageSquareText, ShieldAlert, Smartphone } from 'lucide-react';
import { useAuth } from '../../auth/AuthProvider';
import AccountHeading from '../../components/account/AccountHeading';
import AuthAlert from '../../components/auth/AuthAlert';
import { Button } from '../../components/ui/Button';
import { useDocumentTitle } from '../../hooks/useDocumentTitle';
import { useTranslation } from '../../i18n';
import { userApi } from '../../services/apiClient';

export default function NotificationPreferencesPage() {
  const { user, refreshProfile } = useAuth(); const { t } = useTranslation(); const initial = user.preferences?.notifications || {}; const [preferences, setPreferences] = useState({ inApp: initial.inApp ?? true, email: initial.email ?? true, push: initial.push ?? false, sms: initial.sms ?? true, security: true, marketing: initial.marketing ?? false }); const [saving, setSaving] = useState(false); const [saved, setSaved] = useState(false); useDocumentTitle(t('dashboard.notifications'));
  const channels = [{ key: 'inApp', icon: Bell, label: 'In-app notifications', body: 'Account, message, listing, support, payment, and promotion updates.' }, { key: 'email', icon: Mail, label: 'Email notifications', body: 'Verification, account recovery, receipts, and selected activity.' }, { key: 'sms', icon: MessageSquareText, label: 'SMS notifications', body: 'OTP, critical account activity, and opted-in transactional alerts.' }, { key: 'push', icon: Smartphone, label: 'Push notifications', body: 'Prepared for future QAVLIO web and mobile applications.' }, { key: 'marketing', icon: CheckCircle2, label: 'Deals and product updates', body: 'Optional marketing messages. Transactional messages are managed separately.' }];
  async function save() { setSaving(true); setSaved(false); try { await userApi.updateNotifications(preferences); await refreshProfile(); setSaved(true); } finally { setSaving(false); } }
  return <><AccountHeading title={t('dashboard.notifications')} description="Choose how QAVLIO keeps you informed. Security alerts remain enabled for account protection." />{saved && <div className="mb-5"><AuthAlert type="success" title="Notification preferences updated" /></div>}<section className="rounded-2xl border border-ink-900/10 bg-white p-5 shadow-sm sm:p-7"><div className="space-y-3">{channels.map(({ key,icon: Icon,label,body }) => <label key={key} className="flex cursor-pointer items-center gap-4 rounded-xl border border-slate-200 p-4"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-violet-50 text-violet-700"><Icon size={18} /></span><span className="min-w-0 flex-1"><strong className="block text-xs">{label}</strong><span className="mt-1 block text-[10px] leading-4 text-slate-500">{body}</span></span><input type="checkbox" checked={preferences[key]} onChange={(event) => setPreferences({ ...preferences, [key]: event.target.checked })} className="h-5 w-5 accent-violet-600" /></label>)}</div><div className="mt-4 flex items-center gap-3 rounded-xl bg-amber-50 p-4 text-amber-800"><ShieldAlert size={19} className="shrink-0" /><p className="text-[10px] leading-5"><strong>Security alerts stay on.</strong> Password, session, verification, and high-risk account changes may be sent regardless of marketing preferences.</p></div><div className="mt-6 flex justify-end"><Button onClick={save} disabled={saving}>{saving ? t('common.loading') : t('common.save')}</Button></div></section></>;
}
