import { KeyRound, Laptop, Link2, LogOut, MapPin, Smartphone, Trash2, UserX } from 'lucide-react';
import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../../auth/AuthProvider';
import AccountHeading from '../../components/account/AccountHeading';
import AuthAlert from '../../components/auth/AuthAlert';
import PasswordField from '../../components/auth/PasswordField';
import PasswordStrength, { passwordChecks } from '../../components/auth/PasswordStrength';
import { Button } from '../../components/ui/Button';
import { Modal } from '../../components/ui/Modal';
import { accountLinkApi, userApi } from '../../services/apiClient';
import type { SessionPreview } from '../../types/auth';
import { useDocumentTitle } from '../../hooks/useDocumentTitle';

const formatDate = (value: string) => value ? new Intl.DateTimeFormat('en-PK', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : 'Unknown';
type Message = { type: 'success' | 'error' | 'info'; text: string };
export default function SecurityPage() {
  const { clearSession } = useAuth(); const navigate = useNavigate(); const [sessions, setSessions] = useState<SessionPreview[]>([]); const [loadingSessions, setLoadingSessions] = useState(true); const [message, setMessage] = useState<Message | null>(null);
  const [passwordForm, setPasswordForm] = useState({ currentPassword: '', password: '', confirmPassword: '' }); const [changing, setChanging] = useState(false);
  const [danger, setDanger] = useState<'logout' | 'deactivate' | 'delete' | null>(null); const [dangerPassword, setDangerPassword] = useState(''); const [confirmation, setConfirmation] = useState(''); const [dangerBusy, setDangerBusy] = useState(false);
  const [linkForm, setLinkForm] = useState({ phone: '', password: '', linkRequestId: '', code: '', confirmation: '' }); const [linking, setLinking] = useState(false); useDocumentTitle('Security and sessions');
  const loadSessions = useCallback(async () => { try { const response = await userApi.sessions(); setSessions(response.data); } catch (error) { setMessage({ type: 'error', text: error instanceof Error ? error.message : 'Sessions failed to load.' }); } finally { setLoadingSessions(false); } }, []);
  useEffect(() => { void loadSessions(); }, [loadSessions]);
  async function revoke(session: SessionPreview) { try { await userApi.revokeSession(session.id); if (session.current) { clearSession(); navigate('/login', { replace: true }); } else setSessions((items) => items.filter((item) => item.id !== session.id)); } catch (error) { setMessage({ type: 'error', text: error instanceof Error ? error.message : 'Session could not be revoked.' }); } }
  async function changePassword(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (passwordForm.password !== passwordForm.confirmPassword) { setMessage({ type: 'error', text: 'Passwords do not match.' }); return; } if (!passwordChecks(passwordForm.password).every((item) => item.passed)) { setMessage({ type: 'error', text: 'Create a stronger password.' }); return; } setChanging(true); setMessage(null); try { await userApi.changePassword(passwordForm); clearSession(); navigate('/login', { replace: true, state: { passwordChanged: true } }); } catch (error) { setMessage({ type: 'error', text: error instanceof Error ? error.message : 'Password change failed.' }); } finally { setChanging(false); } }
  async function applyDanger() { if (!danger) return; setDangerBusy(true); try { if (danger === 'logout') await userApi.revokeAllSessions(); if (danger === 'deactivate') await userApi.deactivateAccount({ password: dangerPassword, confirmation }); if (danger === 'delete') await userApi.deleteAccount({ password: dangerPassword, confirmation }); clearSession(); navigate(danger === 'logout' ? '/login' : '/', { replace: true }); } catch (error) { setMessage({ type: 'error', text: error instanceof Error ? error.message : 'Account action failed.' }); setDanger(null); setDangerPassword(''); setConfirmation(''); setDangerBusy(false); } }
  async function initiateLink(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLinking(true); setMessage(null); try { const response = await accountLinkApi.initiate({ phone: linkForm.phone, password: linkForm.password }); setLinkForm({ ...linkForm, linkRequestId: response.data.linkRequestId, phone: response.data.phone, password: '' }); setMessage({ type: 'info', text: response.data.warning }); } catch (error) { setMessage({ type: 'error', text: error instanceof Error ? error.message : 'Account-link request failed.' }); } finally { setLinking(false); } }
  async function confirmLink(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLinking(true); try { const response = await accountLinkApi.confirm({ linkRequestId: linkForm.linkRequestId, code: linkForm.code, confirmation: linkForm.confirmation }); setMessage({ type: 'success', text: response.data.message }); setLinkForm({ phone: '', password: '', linkRequestId: '', code: '', confirmation: '' }); } catch (error) { setMessage({ type: 'error', text: error instanceof Error ? error.message : 'Account-link confirmation failed.' }); } finally { setLinking(false); } }
  const phrase = danger === 'deactivate' ? 'DELETE' : danger === 'delete' ? 'DELETE ACCOUNT' : '';
  return <><AccountHeading title="Security and sessions" description="Control your password, active devices, duplicate identity review, and sensitive account actions." />{message && <div className="mb-5"><AuthAlert type={message.type} title={message.text} /></div>}<div className="space-y-5"><section className="rounded-2xl border border-ink-900/10 bg-white p-5 shadow-sm sm:p-7"><div className="flex items-center justify-between gap-3"><div><h2 className="text-base font-extrabold">Active sessions</h2><p className="mt-1 text-[10px] text-slate-500">Refresh credentials remain in secure HttpOnly cookies.</p></div><Button variant="secondary" size="sm" onClick={() => setDanger('logout')} disabled={!sessions.length}><LogOut size={14} />Log out all</Button></div><div className="mt-5 space-y-3">{loadingSessions ? <div className="h-20 animate-pulse rounded-xl bg-slate-100" /> : sessions.map((session) => <article key={session.id} className="flex flex-col gap-3 rounded-xl border border-slate-200 p-4 sm:flex-row sm:items-center"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-violet-50 text-violet-700">{session.platform === 'Android' || session.platform === 'iOS' ? <Smartphone size={19} /> : <Laptop size={19} />}</span><div className="min-w-0 flex-1"><p className="flex flex-wrap items-center gap-2 text-xs font-extrabold">{session.browser} — {session.platform}{session.current && <span className="rounded-full bg-emerald-50 px-2 py-1 text-[8px] text-emerald-700">Current device</span>}</p><p className="mt-1 flex flex-wrap gap-x-4 gap-y-1 text-[9px] text-slate-400"><span>Last active: {formatDate(session.lastActiveAt)}</span><span className="inline-flex items-center gap-1"><MapPin size={10} />{session.approximateLocation}</span></p></div><button type="button" onClick={() => { void revoke(session); }} className="self-start rounded-lg border border-slate-200 px-3 py-2 text-[10px] font-extrabold text-slate-600 hover:text-rose-600 sm:self-auto">Log out device</button></article>)}{!loadingSessions && !sessions.length && <p className="rounded-xl bg-slate-50 p-4 text-xs text-slate-500">No active sessions found.</p>}</div></section>
    <section className="grid gap-5 xl:grid-cols-2"><form onSubmit={changePassword} className="rounded-2xl border border-ink-900/10 bg-white p-5 shadow-sm sm:p-7"><KeyRound className="text-violet-600" /><h2 className="mt-4 text-base font-extrabold">Change password</h2><div className="mt-5 space-y-4"><PasswordField label="Current password" autoComplete="current-password" value={passwordForm.currentPassword} onChange={(event) => setPasswordForm({ ...passwordForm, currentPassword: event.target.value })} required /><div><PasswordField label="New password" autoComplete="new-password" value={passwordForm.password} onChange={(event) => setPasswordForm({ ...passwordForm, password: event.target.value })} required /><PasswordStrength password={passwordForm.password} /></div><PasswordField label="Confirm password" autoComplete="new-password" value={passwordForm.confirmPassword} onChange={(event) => setPasswordForm({ ...passwordForm, confirmPassword: event.target.value })} required /><Button type="submit" loading={changing} className="w-full">Change password</Button></div></form><section className="rounded-2xl border border-ink-900/10 bg-white p-5 shadow-sm sm:p-7"><Link2 className="text-blue-600" /><h2 className="mt-4 text-base font-extrabold">Account linking</h2><p className="mt-2 text-[10px] leading-5 text-slate-500">Duplicate identities require your password, a request-bound OTP, exact confirmation, and human review. Accounts are never merged automatically.</p>{!linkForm.linkRequestId ? <form onSubmit={initiateLink} className="mt-5 space-y-3"><input type="tel" className="input-base" placeholder="Phone on the other account" value={linkForm.phone} onChange={(event) => setLinkForm({ ...linkForm, phone: event.target.value })} required /><PasswordField label="Current password" value={linkForm.password} onChange={(event) => setLinkForm({ ...linkForm, password: event.target.value })} required /><Button type="submit" variant="secondary" loading={linking} className="w-full">Verify identity to link</Button></form> : <form onSubmit={confirmLink} className="mt-5 space-y-3"><input inputMode="numeric" maxLength={6} className="input-base" placeholder="Six-digit OTP" value={linkForm.code} onChange={(event) => setLinkForm({ ...linkForm, code: event.target.value.replace(/\D/g, '') })} required /><input className="input-base" placeholder="Type LINK ACCOUNTS" value={linkForm.confirmation} onChange={(event) => setLinkForm({ ...linkForm, confirmation: event.target.value })} required /><Button type="submit" variant="danger" loading={linking} disabled={linkForm.confirmation !== 'LINK ACCOUNTS'} className="w-full">Submit linking review</Button></form>}</section></section>
    <section className="rounded-2xl border border-rose-200 bg-rose-50 p-5 sm:p-7"><Trash2 className="text-rose-700" /><h2 className="mt-4 text-base font-extrabold text-rose-900">Account actions</h2><p className="mt-2 text-xs leading-5 text-rose-800/70">Deactivation hides your account and can be reviewed by support. Deletion anonymizes optional profile information and cannot be undone.</p><div className="mt-4 flex flex-wrap gap-2"><Button variant="secondary" onClick={() => setDanger('deactivate')}><UserX size={15} /> Deactivate account</Button><Button variant="danger" onClick={() => setDanger('delete')}><Trash2 size={15} /> Delete account</Button></div></section>
  </div><Modal open={Boolean(danger)} title={danger === 'logout' ? 'Log out every device?' : danger === 'delete' ? 'Permanently delete account?' : 'Deactivate account?'} description={danger === 'logout' ? 'Every active session, including this one, will be closed.' : `Re-enter your password and type ${phrase} exactly.`} onClose={() => { if (!dangerBusy) { setDanger(null); setConfirmation(''); setDangerPassword(''); } }}><div className="space-y-4">{danger !== 'logout' && <><PasswordField label="Current password" value={dangerPassword} onChange={(event) => setDangerPassword(event.target.value)} /><label className="block text-xs font-extrabold">Type {phrase}<input className="input-base mt-2" value={confirmation} onChange={(event) => setConfirmation(event.target.value)} /></label></>}<div className="flex justify-end gap-2"><Button variant="secondary" onClick={() => { setDanger(null); setDangerPassword(''); setConfirmation(''); }} disabled={dangerBusy}>Cancel</Button><Button variant={danger === 'delete' ? 'danger' : 'primary'} onClick={() => { void applyDanger(); }} loading={dangerBusy} disabled={danger !== 'logout' && (!dangerPassword || confirmation !== phrase)}>Confirm</Button></div></div></Modal></>;
}
