import { ArrowLeft, ArrowRight, BadgeCheck, BriefcaseBusiness, Check, MapPin, MessageCircle, ShieldCheck, UserRound } from 'lucide-react';
import { useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { useAuth } from '../../auth/AuthProvider';
import AuthAlert from '../../components/auth/AuthAlert';
import { Button } from '../../components/ui/Button';
import Logo from '../../components/ui/Logo';
import { useDocumentTitle } from '../../hooks/useDocumentTitle';
import { userApi } from '../../services/apiClient';

type SellerForm = { accountType: 'individual' | 'business'; displayName: string; businessName: string; description: string; location: { country: string; province: string; city: string; area: string }; contactPreference: 'chat' | 'chat_and_call' | 'call'; acceptSellerPolicy: boolean };
const labels = ['Profile', 'Information', 'Location', 'Contact', 'Review', 'Ready'];
export default function SellerOnboardingPage() {
  const { user, updateLocalUser } = useAuth(); const account = user!; const navigate = useNavigate(); const [searchParams] = useSearchParams();
  const [step, setStep] = useState(1); const [form, setForm] = useState<SellerForm>({ accountType: 'individual', displayName: account.seller?.businessName || account.name, businessName: '', description: account.about || '', location: { ...account.location }, contactPreference: 'chat', acceptSellerPolicy: false });
  const [submitting, setSubmitting] = useState(false); const [error, setError] = useState<string | null>(null); useDocumentTitle('Seller onboarding');
  const next = () => { setError(null); if (step === 1 && !form.displayName.trim()) { setError('Add a seller display name.'); return; } if (step === 2 && form.description.trim().length < 20) { setError('Add at least 20 characters about what you sell.'); return; } if (step === 3 && !form.location.city.trim()) { setError('Add your city.'); return; } setStep((value) => Math.min(5, value + 1)); };
  async function submit() { if (!form.acceptSellerPolicy) return; setSubmitting(true); setError(null); try { const response = await userApi.completeSellerOnboarding(form); updateLocalUser(response.data); setStep(6); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Seller onboarding failed.'); } finally { setSubmitting(false); } }
  return <div className="min-h-screen bg-surface"><header className="border-b border-slate-200 bg-white"><div className="container-shell flex h-[72px] items-center"><Logo /><span className="ml-auto rounded-full bg-violet-50 px-3 py-1.5 text-[10px] font-extrabold text-violet-700">Seller onboarding</span></div></header><main className="container-shell py-8 sm:py-10"><div className="mx-auto max-w-3xl"><div className="text-center"><p className="eyebrow">Grow with QAVLIO</p><h1 className="mt-2 text-3xl font-extrabold sm:text-4xl">Build your seller profile.</h1><p className="mx-auto mt-3 max-w-xl text-sm leading-6 text-slate-500">Your customer identity stays the same. Seller tools are added to the account you already control.</p></div><ol className="hide-scrollbar mt-8 flex gap-2 overflow-x-auto" aria-label="Seller onboarding progress">{labels.map((label, index) => <li key={label} className={`min-w-24 flex-1 rounded-xl p-3 text-center text-[9px] font-extrabold ${step === index + 1 ? 'bg-violet-600 text-white' : step > index + 1 ? 'bg-emerald-100 text-emerald-700' : 'bg-white text-slate-400'}`}>{step > index + 1 ? <Check size={14} className="mx-auto" /> : `${index + 1}. ${label}`}</li>)}</ol>{error && <div className="mx-auto mt-5 max-w-xl"><AuthAlert title={error} /></div>}<section className="mx-auto mt-5 max-w-xl rounded-3xl border border-ink-900/10 bg-white p-6 shadow-card sm:p-8">
    {step === 1 && <div><UserRound className="text-violet-700" /><h2 className="mt-4 text-lg font-extrabold">Create seller profile</h2><div className="mt-5 grid grid-cols-2 gap-3">{[{ id: 'individual' as const, icon: UserRound, title: 'Individual', body: 'Personal or occasional sales' }, { id: 'business' as const, icon: BriefcaseBusiness, title: 'Business', body: 'Store or regular inventory' }].map(({ id, icon: Icon, title, body }) => <button type="button" key={id} onClick={() => setForm({ ...form, accountType: id })} className={`rounded-2xl border p-4 text-left ${form.accountType === id ? 'border-violet-500 bg-violet-50 ring-2 ring-violet-500/10' : 'border-slate-200'}`} aria-pressed={form.accountType === id}><Icon size={20} className="text-violet-700" /><strong className="mt-3 block text-xs">{title}</strong><span className="mt-1 block text-[9px] text-slate-500">{body}</span></button>)}</div><label className="mt-4 block text-xs font-extrabold">Seller display name<input className="input-base mt-2" maxLength={120} value={form.displayName} onChange={(event) => setForm({ ...form, displayName: event.target.value, businessName: form.accountType === 'business' ? event.target.value : '' })} required /></label></div>}
    {step === 2 && <div><BriefcaseBusiness className="text-violet-700" /><h2 className="mt-4 text-lg font-extrabold">Add seller information</h2><p className="mt-1 text-xs text-slate-500">Explain what people can expect from you without sharing private contact details.</p><label className="mt-5 block text-xs font-extrabold">Description<textarea className="input-base mt-2 min-h-32 py-3" maxLength={1200} value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} placeholder="Describe the kinds of items or services you offer..." /></label></div>}
    {step === 3 && <div><MapPin className="text-violet-700" /><h2 className="mt-4 text-lg font-extrabold">Set your location</h2><p className="mt-1 text-xs text-slate-500">Use a city and area—not a precise home address.</p><div className="mt-5 grid gap-3 sm:grid-cols-2"><label className="text-xs font-extrabold">Province<input className="input-base mt-2" value={form.location.province} onChange={(event) => setForm({ ...form, location: { ...form.location, province: event.target.value } })} /></label><label className="text-xs font-extrabold">City<input className="input-base mt-2" value={form.location.city} onChange={(event) => setForm({ ...form, location: { ...form.location, city: event.target.value } })} required /></label><label className="text-xs font-extrabold sm:col-span-2">Area / locality<input className="input-base mt-2" value={form.location.area} onChange={(event) => setForm({ ...form, location: { ...form.location, area: event.target.value } })} /></label></div></div>}
    {step === 4 && <div><MessageCircle className="text-violet-700" /><h2 className="mt-4 text-lg font-extrabold">Choose contact preferences</h2><div className="mt-5 space-y-2">{[{ id: 'chat' as const, label: 'QAVLIO chat only' }, { id: 'chat_and_call' as const, label: 'Chat and call' }, { id: 'call' as const, label: 'Call preferred' }].map((item) => <label key={item.id} className="flex cursor-pointer items-center gap-3 rounded-xl border border-slate-200 p-4 text-xs font-bold"><input type="radio" name="contact" checked={form.contactPreference === item.id} onChange={() => setForm({ ...form, contactPreference: item.id })} className="accent-violet-600" />{item.label}</label>)}</div><p className="mt-3 text-[10px] leading-5 text-slate-500">Sensitive personal information is never added to the public seller profile automatically.</p></div>}
    {step === 5 && <div><ShieldCheck className="text-violet-700" /><h2 className="mt-4 text-lg font-extrabold">Review seller standards</h2><ul className="mt-4 space-y-3 text-xs leading-5 text-slate-600">{['Use accurate titles, prices, photos, and item condition.', 'Respond respectfully and keep conversations on QAVLIO.', 'Never request OTPs, passwords, or unsafe advance payments.', 'Verification badges are earned through separate checks.'].map((item) => <li key={item} className="flex gap-2"><Check size={15} className="mt-0.5 shrink-0 text-emerald-600" />{item}</li>)}</ul><label className="mt-5 flex items-start gap-2 rounded-xl bg-slate-50 p-3 text-[10px] font-semibold leading-5 text-slate-600"><input type="checkbox" checked={form.acceptSellerPolicy} onChange={(event) => setForm({ ...form, acceptSellerPolicy: event.target.checked })} className="mt-0.5 h-4 w-4 accent-violet-600" />I agree to QAVLIO seller standards and understand that listings remain subject to review.</label></div>}
    {step === 6 && <div className="text-center"><span className="mx-auto grid h-16 w-16 place-items-center rounded-2xl bg-emerald-100 text-emerald-700"><BadgeCheck size={30} /></span><h2 className="mt-5 text-2xl font-extrabold">Seller profile complete</h2><p className="mt-3 text-sm leading-6 text-slate-500">Your seller workspace is ready. Identity and business verification remain separate earned checks.</p><Button onClick={() => { const target = searchParams.get('returnTo'); navigate(target?.startsWith('/') && !target.startsWith('//') ? target : '/seller', { replace: true }); }} className="mt-6 w-full">Open seller dashboard <ArrowRight size={16} /></Button></div>}
    {step < 6 && <div className="mt-6 flex gap-2">{step > 1 && <Button variant="secondary" onClick={() => setStep((value) => value - 1)}><ArrowLeft size={15} /> Back</Button>}<div className="ml-auto">{step < 5 ? <Button onClick={next}>Continue <ArrowRight size={15} /></Button> : <Button onClick={submit} loading={submitting} disabled={!form.acceptSellerPolicy}>Complete profile</Button>}</div></div>}
  </section></div></main></div>;
}
