import React, { useState } from 'react';
import { ArrowRight, Building2, MailCheck, Phone, ShieldCheck, UserCheck } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../../auth/AuthProvider';
import AccountHeading from '../../components/account/AccountHeading';
import VerificationBadge from '../../components/account/VerificationBadge';
import AuthAlert from '../../components/auth/AuthAlert';
import { Button } from '../../components/ui/Button';
import { useDocumentTitle } from '../../hooks/useDocumentTitle';
import { useTranslation } from '../../i18n';
import { userApi } from '../../services/apiClient';

export default function VerificationCenterPage() {
  const { user } = useAuth(); const { t } = useTranslation(); const navigate = useNavigate(); const [phone, setPhone] = useState(user.phone || ''); const [sending, setSending] = useState(false); const [error, setError] = useState(null); useDocumentTitle(t('profile.trustCenter'));
  const items = [{ key: 'email', icon: MailCheck, label: t('profile.emailVerified'), description: 'Confirms access to your email and account recovery.' }, { key: 'phone', icon: Phone, label: t('profile.phoneVerified'), description: 'Confirms a reachable phone for safer marketplace contact.' }, { key: 'identity', icon: UserCheck, label: t('profile.identityVerified'), description: 'Government identity review will be handled by a protected verification workflow.' }, { key: 'business', icon: Building2, label: t('profile.businessVerified'), description: 'Business registration and ownership checks for professional stores.' }];
  async function requestPhone() { setSending(true); setError(null); try { const response = await userApi.requestPhoneVerification(phone); if (response.data.alreadyVerified) return; const params = new URLSearchParams({ phone: response.data.phone, target: response.data.phone, purpose: response.data.purpose, returnTo: '/account/verification' }); navigate(`/verify-otp?${params}`); } catch (requestError) { setError(requestError); } finally { setSending(false); } }
  return <><AccountHeading title={t('profile.trustCenter')} description="Verification is transparent and earned. QAVLIO never awards trust badges automatically." /><div className="grid gap-5 xl:grid-cols-[1fr_310px]"><section className="rounded-2xl border border-ink-900/10 bg-white p-5 shadow-sm sm:p-7"><div className="space-y-3">{items.map(({ key,icon: Icon,label,description }) => { const status = user.verification?.[key]?.status || 'not_verified'; return <article key={key} className="flex flex-col gap-4 rounded-xl border border-slate-200 p-4 sm:flex-row sm:items-center"><span className={`grid h-11 w-11 shrink-0 place-items-center rounded-xl ${status === 'verified' ? 'bg-emerald-100 text-emerald-700' : 'bg-violet-50 text-violet-700'}`}><Icon size={20} /></span><div className="min-w-0 flex-1"><h2 className="text-sm font-extrabold">{label}</h2><p className="mt-1 text-[10px] leading-5 text-slate-500">{description}</p></div><VerificationBadge label={label} status={status} /></article>; })}</div></section><aside className="space-y-4"><section className="rounded-2xl border border-violet-200 bg-violet-50 p-5"><Phone size={20} className="text-violet-700" /><h2 className="mt-4 text-sm font-extrabold">{user.phone ? 'Change or re-verify phone' : t('profile.addPhone')}</h2><p className="mt-2 text-[10px] leading-5 text-violet-900/60">Pakistan numbers are normalized to international format. A six-digit OTP expires after ten minutes.</p>{error && <div className="mt-3"><AuthAlert title={error.message}>{error.code === 'PHONE_LINKING_REQUIRED' ? 'Use the secure account-linking flow in Security settings.' : null}</AuthAlert></div>}<label htmlFor="verification-phone" className="sr-only">{t('common.phone')}</label><input id="verification-phone" type="tel" className="input-base mt-4" value={phone} onChange={(event) => setPhone(event.target.value)} placeholder="0300 1234567" /><Button onClick={requestPhone} disabled={sending || !phone} className="mt-3 w-full">{sending ? t('auth.sendingOtp') : t('profile.verifyPhone')}<ArrowRight size={15} /></Button></section><section className="rounded-2xl bg-ink-950 p-5 text-white"><ShieldCheck className="text-gold-300" /><h2 className="mt-4 text-sm font-extrabold">What verification means</h2><p className="mt-2 text-[10px] leading-5 text-white/55">Each badge names the check performed. It does not guarantee an item or transaction. Always inspect before paying.</p></section></aside></div></>;
}
