import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { PackageCheck, Plus, Save, X } from 'lucide-react';
import { useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import DashboardLayout from '../../layouts/DashboardLayout';
import AdminEmptyState from '../../components/admin/AdminEmptyState';
import { adminCommandApi } from '../../services/apiClient';
import { formatPrice } from '../../utils/formatters';
import { useDocumentTitle } from '../../hooks/useDocumentTitle';
const blank={name:'',description:'',price:0,currency:'PKR',listingCredits:0,promotionCredits:0,promotionDays:0,validityDays:365,features:[],active:true,sortOrder:10};
export default function AdminPackagesPage(){useDocumentTitle('Package management');const client=useQueryClient();const query=useQuery({queryKey:['admin-command-packages'],queryFn:async()=>(await adminCommandApi.packages()).data});const[params]=useSearchParams();const[open,setOpen]=useState(params.get('action')==='create'),[draft,setDraft]=useState<any>(blank);const create=useMutation({mutationFn:()=>adminCommandApi.createPackage(draft),onSuccess:()=>{setOpen(false);setDraft(blank);void client.invalidateQueries({queryKey:['admin-command-packages']})}});return <DashboardLayout role="admin"><div className="flex flex-wrap items-end justify-between gap-3"><header><p className="eyebrow">Seller monetization</p><h1 className="mt-2 text-3xl font-extrabold">Packages</h1><p className="mt-2 text-sm text-slate-500">Create, edit or deactivate packages. Historical purchases remain unchanged.</p></header><button onClick={()=>setOpen(true)} className="inline-flex h-11 items-center gap-2 rounded-control bg-violet-600 px-4 text-xs font-extrabold text-white"><Plus size={15}/>Create package</button></div>{open&&<section className="mt-6 rounded-panel border border-violet-200 bg-violet-50 p-5"><div className="flex justify-between"><h2 className="font-extrabold">New package</h2><button onClick={()=>setOpen(false)} aria-label="Close"><X size={17}/></button></div><Fields item={draft} onChange={setDraft}/><button onClick={()=>create.mutate()} disabled={draft.name.length<2||draft.description.length<5||create.isPending} className="mt-4 h-10 rounded-control bg-ink-950 px-5 text-xs font-extrabold text-white disabled:opacity-50">Create</button>{create.error&&<p role="alert" className="mt-2 text-xs font-bold text-red-600">{create.error.message}</p>}</section>}{query.isLoading?<div className="mt-6 h-64 animate-pulse rounded-panel bg-slate-200"/>:query.data?.length?<div className="mt-6 grid gap-4 xl:grid-cols-2">{query.data.map((item:any)=><Editor key={item.id} item={item} onSaved={()=>client.invalidateQueries({queryKey:['admin-command-packages']})}/>)}</div>:<div className="mt-6"><AdminEmptyState title="No packages" text="Create the first seller package."/></div>}</DashboardLayout>}
function Fields({item,onChange}:{item:any;onChange:(value:any)=>void}){const set=(key:string,value:any)=>onChange({...item,[key]:value});return <div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><label className="text-[10px] font-bold">Name<input value={item.name} onChange={e=>set('name',e.target.value)} className="input-base mt-1 !h-10"/></label><label className="text-[10px] font-bold sm:col-span-2">Description<input value={item.description} onChange={e=>set('description',e.target.value)} className="input-base mt-1 !h-10"/></label>{[['Price', 'price'],['Listing credits','listingCredits'],['Promotion credits','promotionCredits'],['Featured days','promotionDays'],['Validity days','validityDays']].map(([label,key])=><label key={key} className="text-[10px] font-bold">{label}<input type="number" min="0" value={item[key]} onChange={e=>set(key,Number(e.target.value))} className="input-base mt-1 !h-10"/></label>)}<label className="text-[10px] font-bold sm:col-span-2">Features (one per line)<textarea value={(item.features||[]).join('\n')} onChange={e=>set('features',e.target.value.split('\n').map(x=>x.trim()).filter(Boolean))} className="input-base mt-1 min-h-20 py-2"/></label><label className="flex items-center gap-2 text-xs font-bold"><input type="checkbox" checked={item.active} onChange={e=>set('active',e.target.checked)}/>Active</label></div>}
function Editor({item,onSaved}:{item:any;onSaved:()=>void}){const[draft,setDraft]=useState(item);const save=useMutation({mutationFn:()=>adminCommandApi.updatePackage(item.id,{name:draft.name,description:draft.description,price:draft.price,currency:draft.currency,listingCredits:draft.listingCredits,promotionCredits:draft.promotionCredits,promotionDays:draft.promotionDays,validityDays:draft.validityDays,features:draft.features,active:draft.active,sortOrder:draft.sortOrder}),onSuccess:onSaved});return <article className="rounded-panel border bg-white p-5"><div className="flex items-start justify-between gap-3"><div className="flex gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-violet-50 text-violet-600"><PackageCheck size={18}/></span><div><h2 className="font-extrabold">{draft.name}</h2><p className="mt-1 text-[10px] text-slate-500">{formatPrice(draft.price,draft.currency)} · {draft.active?'Active':'Inactive'}</p></div></div><button onClick={()=>save.mutate()} className="inline-flex h-9 items-center gap-1 rounded-control border px-3 text-[10px] font-extrabold"><Save size={12}/>Save</button></div><Fields item={draft} onChange={setDraft}/></article>}
