import { useQuery } from '@tanstack/react-query';
import { AlertTriangle, BadgeCheck, FileWarning, ShieldAlert, Store } from 'lucide-react';
import { Link } from 'react-router-dom';
import AdminEmptyState from '../../components/admin/AdminEmptyState';
import AdminStatCard from '../../components/admin/AdminStatCard';
import DashboardLayout from '../../layouts/DashboardLayout';
import { adminCommandApi } from '../../services/apiClient';
import { useDocumentTitle } from '../../hooks/useDocumentTitle';
export default function AdminTrustSafetyPage(){useDocumentTitle('Trust & Safety');const query=useQuery({queryKey:['admin-trust-safety'],queryFn:async()=>(await adminCommandApi.trustSafety()).data});const data=query.data;return <DashboardLayout role="admin"><header><p className="eyebrow">Marketplace integrity</p><h1 className="mt-2 text-3xl font-extrabold">Trust & Safety</h1><p className="mt-2 text-sm text-slate-500">Risk signals are decision support—not automatic guilt or fabricated fraud conclusions.</p></header>{query.isLoading?<div className="mt-6 h-72 animate-pulse rounded-panel bg-slate-200"/>:<><section className="mt-6 grid grid-cols-2 gap-3 xl:grid-cols-5"><AdminStatCard icon={ShieldAlert} label="High-risk listings" value={data?.highRiskListings?.length||0} tone="rose"/><AdminStatCard icon={AlertTriangle} label="Suspicious signals" value={data?.suspiciousActivity?.length||0} tone="amber"/><AdminStatCard icon={BadgeCheck} label="Verification queue" value={data?.verificationQueue?.length||0}/><AdminStatCard icon={FileWarning} label="Repeated reports" value={data?.repeatedReports?.length||0} tone="rose"/><AdminStatCard icon={Store} label="Restricted sellers" value={data?.restrictedSellers?.length||0} tone="amber"/></section><div className="mt-6 grid gap-5 xl:grid-cols-2"><Queue title="High-risk listing signals" items={data?.highRiskListings} render={(item:any)=><Link to={`/admin/listings?search=${item.listingId}`} className="font-bold text-violet-700">{item.listingId} · {item.riskLevel}</Link>}/><Queue title="Verification queue" items={data?.verificationQueue} render={(item:any)=><Link to={`/admin/sellers?search=${item.displayName}`} className="font-bold text-violet-700">{item.displayName}</Link>}/><Queue title="Repeated reports" items={data?.repeatedReports} render={(item:any)=><span className="font-bold">{item.name} · {item.count} reports</span>}/><Queue title="Restricted sellers" items={data?.restrictedSellers} render={(item:any)=><span className="font-bold">{item.displayName||item.publicSlug||item.userId}</span>}/></div></>}</DashboardLayout>}
function Queue({title,items=[],render}:{title:string;items:any[];render:(item:any)=>React.ReactNode}){return <section className="rounded-panel border bg-white p-5"><h2 className="font-extrabold">{title}</h2>{items.length?<div className="mt-4 divide-y">{items.slice(0,10).map((item:any,index:number)=><div key={item.id||item.name||index} className="py-3 text-xs">{render(item)}</div>)}</div>:<div className="mt-4"><AdminEmptyState title="Queue clear" text="No tracked records in this queue."/></div>}</section>}
