import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Bot, CreditCard, Megaphone, Save, Settings, ShieldCheck } from 'lucide-react';
import { Link } from 'react-router-dom';
import DashboardLayout from '../../layouts/DashboardLayout';
import { adminControlApi } from '../../services/apiClient';
import { useDocumentTitle } from '../../hooks/useDocumentTitle';
export default function AdminSettingsPage(){useDocumentTitle('Platform settings');const client=useQueryClient();const query=useQuery({queryKey:['admin-settings'],queryFn:async()=>(await adminControlApi.settings()).data});const update=useMutation({mutationFn:({key,value}:{key:string;value:any})=>adminControlApi.updateSetting(key,value),onSuccess:()=>client.invalidateQueries({queryKey:['admin-settings']})});const groups=group(query.data||[]);return <DashboardLayout role="admin"><header><p className="eyebrow">Versioned platform policy</p><h1 className="mt-2 text-3xl font-extrabold">Settings</h1><p className="mt-2 text-sm text-slate-500">General, marketplace, notifications, trust, ads and SEO controls. Every change is validated and audited.</p></header><nav className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4" aria-label="Specialized settings">{[[CreditCard,'Monetization','/admin/settings/monetization'],[Bot,'AI controls','/admin/ai'],[Megaphone,'Advertising','/admin/ads'],[ShieldCheck,'Trust & Safety','/admin/trust-safety']].map(([Icon,label,to]:any)=><Link key={to} to={to} className="flex items-center gap-3 rounded-card border bg-white p-4 text-xs font-extrabold text-violet-700"><Icon size={17}/>{label}</Link>)}</nav>{query.isLoading?<div className="mt-6 h-72 animate-pulse rounded-panel bg-slate-200"/>:<div className="mt-6 grid gap-5 xl:grid-cols-2">{Object.entries(groups).map(([category,items]:any)=><section key={category} className="rounded-panel border bg-white p-5"><h2 className="flex items-center gap-2 font-extrabold capitalize"><Settings size={16} className="text-violet-600"/>{category}</h2><div className="mt-4 divide-y">{items.map((item:any)=><Setting key={item.key} item={item} save={(value)=>update.mutate({key:item.key,value})}/>)}</div></section>)}</div>}{update.error&&<p role="alert" className="mt-4 rounded-card bg-red-50 p-4 text-xs font-bold text-red-700">{update.error.message}</p>}</DashboardLayout>}
function Setting({item,save}:{item:any;save:(value:any)=>void}){return <label className="flex items-center gap-4 py-4"><span className="min-w-0 flex-1"><strong className="block text-xs capitalize">{item.key.replace(/([A-Z])/g,' $1')}</strong><small className="mt-1 block text-[10px] text-slate-500">{item.description}</small></span>{item.type==='boolean'?<input type="checkbox" checked={Boolean(item.value)} onChange={e=>save(e.target.checked)} className="h-5 w-5 accent-violet-600"/>:item.options?<select value={item.value} onChange={e=>save(e.target.value)} className="h-10 rounded-control border px-3 text-xs">{item.options.map((option:string)=><option key={option}>{option}</option>)}</select>:item.type==='number'?<input type="number" defaultValue={item.value} min={item.min} max={item.max} onBlur={e=>Number(e.target.value)!==Number(item.value)&&save(Number(e.target.value))} className="input-base !h-10 w-28"/>:<span className="flex items-center gap-2"><input defaultValue={item.value} onBlur={e=>e.target.value!==item.value&&save(e.target.value)} className="input-base !h-10 w-44"/><Save size={13} className="text-slate-400"/></span>}</label>}
function group(items:any[]){return items.reduce((result,item)=>{(result[item.category]||=[]).push(item);return result},{} as Record<string,any[]>)}
