export const ADMIN_PERMISSIONS = {
  DASHBOARD_VIEW: 'dashboard:view',
  USERS_VIEW: 'users:view', USERS_MANAGE: 'users:manage',
  SELLERS_VIEW: 'sellers:view', SELLERS_MANAGE: 'sellers:manage',
  LISTINGS_VIEW: 'listings:view', LISTINGS_MODERATE: 'listings:moderate',
  CATEGORIES_VIEW: 'categories:view', CATEGORIES_MANAGE: 'categories:manage',
  REPORTS_VIEW: 'reports:view', REPORTS_MANAGE: 'reports:manage',
  TRUST_SAFETY_VIEW: 'trust-safety:view',
  ORDERS_VIEW: 'orders:view',
  FINANCE_VIEW: 'finance:view', FINANCE_REFUND: 'finance:refund',
  PROMOTIONS_MANAGE: 'promotions:manage', PACKAGES_MANAGE: 'packages:manage',
  ADS_MANAGE: 'ads:manage',
  AI_VIEW: 'ai:view', AI_MANAGE: 'ai:manage',
  SUPPORT_VIEW: 'support:view', SUPPORT_MANAGE: 'support:manage',
  ANNOUNCEMENTS_VIEW: 'announcements:view', ANNOUNCEMENTS_MANAGE: 'announcements:manage',
  ANALYTICS_VIEW: 'analytics:view', EXPORT_DATA: 'export:data',
  SETTINGS_VIEW: 'settings:view', SETTINGS_MANAGE: 'settings:manage',
  ACTIVITY_VIEW: 'activity:view',
} as const;
export type AdminPermission = (typeof ADMIN_PERMISSIONS)[keyof typeof ADMIN_PERMISSIONS];
const all = Object.values(ADMIN_PERMISSIONS);
export const ROLE_PERMISSIONS: Record<string, readonly AdminPermission[]> = {
  super_admin: all,
  admin: all.filter((permission) => permission !== ADMIN_PERMISSIONS.FINANCE_REFUND),
  moderator: [ADMIN_PERMISSIONS.DASHBOARD_VIEW, ADMIN_PERMISSIONS.USERS_VIEW, ADMIN_PERMISSIONS.SELLERS_VIEW, ADMIN_PERMISSIONS.LISTINGS_VIEW, ADMIN_PERMISSIONS.LISTINGS_MODERATE, ADMIN_PERMISSIONS.CATEGORIES_VIEW, ADMIN_PERMISSIONS.REPORTS_VIEW, ADMIN_PERMISSIONS.REPORTS_MANAGE, ADMIN_PERMISSIONS.TRUST_SAFETY_VIEW, ADMIN_PERMISSIONS.ANALYTICS_VIEW, ADMIN_PERMISSIONS.ACTIVITY_VIEW],
  support: [ADMIN_PERMISSIONS.DASHBOARD_VIEW, ADMIN_PERMISSIONS.USERS_VIEW, ADMIN_PERMISSIONS.SELLERS_VIEW, ADMIN_PERMISSIONS.REPORTS_VIEW, ADMIN_PERMISSIONS.SUPPORT_VIEW, ADMIN_PERMISSIONS.SUPPORT_MANAGE, ADMIN_PERMISSIONS.ANNOUNCEMENTS_VIEW, ADMIN_PERMISSIONS.ACTIVITY_VIEW],
  finance: [ADMIN_PERMISSIONS.DASHBOARD_VIEW, ADMIN_PERMISSIONS.ORDERS_VIEW, ADMIN_PERMISSIONS.FINANCE_VIEW, ADMIN_PERMISSIONS.FINANCE_REFUND, ADMIN_PERMISSIONS.PACKAGES_MANAGE, ADMIN_PERMISSIONS.ANALYTICS_VIEW, ADMIN_PERMISSIONS.EXPORT_DATA, ADMIN_PERMISSIONS.ACTIVITY_VIEW],
};
