export const DEMO_LISTINGS = [
  { publicId: 'QV-100285', slug: 'iphone-15-pro-256gb', title: 'iPhone 15 Pro 256GB — Natural Titanium', description: 'Box and original accessories included.', price: 245000, currency: 'PKR', categorySlug: 'mobiles', subcategorySlug: 'mobile-phones', condition: 'like-new', location: { city: 'Islamabad', area: 'Blue Area' }, attributes: { brand: 'Apple', storage: '256GB', listingType: 'business' }, status: 'published', viewCount: 1842, isPromoted: true, createdAt: '2026-08-18T08:00:00.000Z' },
  { publicId: 'QV-100284', slug: 'toyota-corolla-altis-2022', title: 'Toyota Corolla Altis 2022', description: 'First owner, complete service history.', price: 6245000, currency: 'PKR', categorySlug: 'cars', subcategorySlug: 'toyota', condition: 'used', location: { city: 'Lahore', area: 'DHA Phase 5' }, attributes: { make: 'Toyota', year: 2022, fuel: 'Petrol', transmission: 'Automatic', listingType: 'individual' }, status: 'published', viewCount: 991, isPromoted: false, createdAt: '2026-08-18T06:00:00.000Z' },
  { publicId: 'QV-100286', slug: 'honda-cb-150f-2023', title: 'Honda CB 150F 2023', description: 'Carefully maintained commuter motorcycle.', price: 495000, currency: 'PKR', categorySlug: 'motorcycles', subcategorySlug: 'honda', condition: 'used', location: { city: 'Islamabad', area: 'F-10' }, attributes: { make: 'Honda', listingType: 'individual' }, status: 'published', viewCount: 620, isPromoted: false, createdAt: '2026-08-17T13:00:00.000Z' },
  { publicId: 'QV-100288', slug: 'macbook-pro-m3-16gb', title: 'MacBook Pro M3 — 16GB / 512GB', description: 'Open box MacBook with local warranty.', price: 389000, currency: 'PKR', categorySlug: 'computers-laptops', subcategorySlug: 'laptops', condition: 'like-new', location: { city: 'Lahore', area: 'Gulberg' }, attributes: { brand: 'Apple', storage: '512GB', listingType: 'business' }, status: 'published', viewCount: 1340, isPromoted: true, createdAt: '2026-08-16T12:00:00.000Z' },
  { publicId: 'QV-100289', slug: 'samsung-55-inch-4k-tv', title: 'Samsung 55-inch 4K Smart TV', description: 'Sealed unit with one year warranty.', price: 139500, currency: 'PKR', categorySlug: 'electronics', subcategorySlug: 'tvs', condition: 'new', location: { city: 'Karachi', area: 'Clifton' }, attributes: { brand: 'Samsung', warranty: true, listingType: 'business' }, status: 'published', viewCount: 744, isPromoted: true, createdAt: '2026-08-15T11:00:00.000Z' },
  { publicId: 'QV-100287', slug: 'modern-nordic-sofa', title: 'Modern Nordic 3-Seater Sofa', description: 'Locally crafted modern sofa in neutral fabric.', price: 68000, currency: 'PKR', categorySlug: 'furniture', subcategorySlug: 'furniture', condition: 'new', location: { city: 'Rawalpindi', area: 'Bahria Town' }, attributes: { listingType: 'business' }, status: 'published', viewCount: 413, isPromoted: false, createdAt: '2026-08-14T09:00:00.000Z' },
  { publicId: 'QV-100290', slug: 'trail-mountain-bike', title: 'Trail Mountain Bike — 27.5 inch', description: 'Lightly used alloy frame mountain bike.', price: 82500, currency: 'PKR', categorySlug: 'other', subcategorySlug: 'sports', condition: 'like-new', location: { city: 'Islamabad', area: 'E-11' }, attributes: { listingType: 'individual' }, status: 'published', viewCount: 365, isPromoted: false, createdAt: '2026-08-13T09:00:00.000Z' },
  { publicId: 'QV-100293', slug: 'custom-gaming-pc-rtx-4070', title: 'Custom Gaming PC — RTX 4070', description: 'Powerful creator and gaming desktop.', price: 425000, currency: 'PKR', categorySlug: 'computers-laptops', subcategorySlug: 'desktop-computers', condition: 'used', location: { city: 'Rawalpindi', area: 'Saddar' }, attributes: { listingType: 'individual' }, status: 'published', viewCount: 1109, isPromoted: false, createdAt: '2026-08-12T07:00:00.000Z' },
  { publicId: 'QV-100310', slug: 'iphone-14-128gb-used', title: 'Apple iPhone 14 128GB — Used', description: 'Used iPhone 14 with original box. Battery health stated as 87%.', price: 142000, currency: 'PKR', categorySlug: 'mobiles', subcategorySlug: 'mobile-phones', condition: 'used', location: { city: 'Karachi', area: 'DHA' }, attributes: { brand: 'Apple', storage: '128GB', listingType: 'individual' }, status: 'published', viewCount: 512, isPromoted: false, createdAt: '2026-08-11T10:00:00.000Z' },
  { publicId: 'QV-100311', slug: 'honda-city-aspire-2018', title: 'Honda City Aspire 2018 — Automatic', description: 'Automatic Honda City with documented service history.', price: 2750000, currency: 'PKR', categorySlug: 'cars', subcategorySlug: 'honda', condition: 'used', location: { city: 'Islamabad', area: 'G-11' }, attributes: { make: 'Honda', year: 2018, fuel: 'Petrol', transmission: 'Automatic', listingType: 'individual' }, status: 'published', viewCount: 803, isPromoted: false, createdAt: '2026-08-10T09:00:00.000Z' },
  { publicId: 'QV-100312', slug: 'hp-pavilion-gaming-rtx-16gb', title: 'HP Pavilion Gaming Laptop — RTX 4050 16GB SSD', description: 'Gaming laptop with RTX GPU, 16GB RAM and SSD storage as listed.', price: 189000, currency: 'PKR', categorySlug: 'computers-laptops', subcategorySlug: 'laptops', condition: 'used', location: { city: 'Lahore', area: 'Johar Town' }, attributes: { brand: 'HP', ram: '16GB', gpu: 'RTX', storageType: 'SSD', useCase: 'Gaming', listingType: 'individual' }, status: 'published', viewCount: 677, isPromoted: false, createdAt: '2026-08-09T12:00:00.000Z' },
  { publicId: 'QV-100313', slug: 'oak-dining-table-islamabad', title: 'Solid Oak Dining Table — 6 Seater', description: 'Locally made dining table. Pickup in Islamabad.', price: 46000, currency: 'PKR', categorySlug: 'furniture', subcategorySlug: 'furniture', condition: 'used', location: { city: 'Islamabad', area: 'I-8' }, attributes: { listingType: 'individual' }, status: 'published', viewCount: 221, isPromoted: false, createdAt: '2026-08-08T08:00:00.000Z' },
];
