export const SECURITY_EVENTS = Object.freeze({
  ACCOUNT_REGISTERED: 'account.registered',
  LOGIN_SUCCEEDED: 'auth.login_succeeded',
  LOGIN_FAILED: 'auth.login_failed',
  LOGOUT: 'auth.logout',
  LOGOUT_ALL: 'auth.logout_all',
  SESSION_REFRESHED: 'auth.session_refreshed',
  OTP_REQUESTED: 'verification.otp_requested',
  OTP_VERIFIED: 'verification.otp_verified',
  OTP_FAILED: 'verification.otp_failed',
  EMAIL_VERIFIED: 'verification.email_verified',
  PASSWORD_RESET_REQUESTED: 'password.reset_requested',
  PASSWORD_RESET_COMPLETED: 'password.reset_completed',
  PASSWORD_CHANGED: 'password.changed',
  PROFILE_UPDATED: 'profile.updated',
  ACCOUNT_DEACTIVATED: 'account.deactivated',
  ACCOUNT_DELETED: 'account.deleted',
  SELLER_ONBOARDING_COMPLETED: 'seller.onboarding_completed',
  AVATAR_UPDATED: 'profile.avatar_updated',
  ACCOUNT_STATUS_CHANGED: 'admin.account_status_changed',
  ROLES_CHANGED: 'admin.roles_changed',
  ACCOUNT_LINK_REQUESTED: 'account_link.requested',
  ACCOUNT_LINK_CONFIRMED: 'account_link.confirmed',
});
