import { RotateCcw } from 'lucide-react';
import type { ReactNode } from 'react';

export interface FilterDefinition { key: string; label: string; type: 'select' | 'multiselect' | 'number' | 'boolean'; options?: string[]; }
interface Props { params: URLSearchParams; dynamicFilters?: FilterDefinition[]; onChange: (key: string, value?: string) => void; onClear: () => void; onApply?: () => void; mobile?: boolean; }
const Group = ({ title, children }: { title: string; children: ReactNode }) => <fieldset className="border-b border-slate-100 py-5 last:border-0"><legend className="mb-3 text-xs font-extrabold text-ink-900">{title}</legend>{children}</fieldset>;
const locations = ['All Pakistan', 'Islamabad', 'Rawalpindi', 'Lahore', 'Karachi', 'Peshawar', 'Quetta'];

export default function FilterPanel({ params, dynamicFilters = [], onChange, onClear, onApply, mobile }: Props) {
  const conditions = params.get('condition')?.split(',').filter(Boolean) || [];
  const toggle = (value: string) => onChange('condition', conditions.includes(value) ? conditions.filter((item) => item !== value).join(',') : [...conditions, value].join(','));
  return <form onSubmit={(event) => { event.preventDefault(); onApply?.(); }} className={mobile ? 'bg-white' : 'rounded-2xl border border-ink-900/10 bg-white p-5 shadow-sm'} aria-label="Listing filters">
    {!mobile && <div className="flex items-center justify-between"><h2 className="text-sm font-extrabold">Filters</h2><button type="button" onClick={onClear} className="inline-flex items-center gap-1 text-[11px] font-bold text-violet-700"><RotateCcw size={12} /> Clear all</button></div>}
    <Group title="Location"><select value={params.get('location') || 'All Pakistan'} onChange={(event) => onChange('location', event.target.value === 'All Pakistan' ? undefined : event.target.value)} className="input-base !h-10 !px-3 !text-xs" aria-label="Location">{locations.map((location) => <option key={location}>{location}</option>)}</select></Group>
    <Group title="Price range"><div className="grid grid-cols-2 gap-2"><input value={params.get('minPrice') || ''} onChange={(event) => onChange('minPrice', event.target.value)} className="input-base !h-10 !px-3 !text-xs" inputMode="numeric" type="number" min="0" placeholder="Minimum" aria-label="Minimum price" /><input value={params.get('maxPrice') || ''} onChange={(event) => onChange('maxPrice', event.target.value)} className="input-base !h-10 !px-3 !text-xs" inputMode="numeric" type="number" min="0" placeholder="Maximum" aria-label="Maximum price" /></div></Group>
    <Group title="Condition"><div className="space-y-2.5">{[['new','New'], ['like-new','Like new'], ['used','Used'], ['refurbished','Refurbished']].map(([value, label]) => <label key={value} className="flex min-h-7 items-center gap-2 text-xs font-semibold text-slate-600"><input type="checkbox" checked={conditions.includes(value)} onChange={() => toggle(value)} className="h-4 w-4 rounded border-slate-300 accent-violet-600" /> {label}</label>)}</div></Group>
    <Group title="Seller"><select value={params.get('listingType') || ''} onChange={(event) => onChange('listingType', event.target.value)} className="input-base !h-10 !px-3 !text-xs"><option value="">Any seller</option><option value="individual">Individual</option><option value="business">Business</option></select></Group>
    <Group title="Date posted"><select value={params.get('date') || ''} onChange={(event) => onChange('date', event.target.value)} className="input-base !h-10 !px-3 !text-xs"><option value="">Any time</option><option value="today">Today</option><option value="3days">Last 3 days</option><option value="7days">Last 7 days</option><option value="30days">Last 30 days</option></select></Group>
    {dynamicFilters.filter((filter) => !['condition', 'listingType'].includes(filter.key)).map((filter) => <Group key={filter.key} title={filter.label}>{filter.type === 'boolean' ? <select value={params.get(`attr.${filter.key}`) || ''} onChange={(event) => onChange(`attr.${filter.key}`, event.target.value)} className="input-base !h-10 !text-xs"><option value="">Any</option><option value="true">Yes</option><option value="false">No</option></select> : filter.options ? <select value={params.get(`attr.${filter.key}`) || ''} onChange={(event) => onChange(`attr.${filter.key}`, event.target.value)} className="input-base !h-10 !text-xs"><option value="">Any</option>{filter.options.map((option) => <option key={option}>{option}</option>)}</select> : <input type="number" value={params.get(`attr.${filter.key}`) || ''} onChange={(event) => onChange(`attr.${filter.key}`, event.target.value)} className="input-base !h-10 !text-xs" />}</Group>)}
    {mobile && <button type="submit" className="mt-5 h-12 w-full rounded-control bg-violet-600 text-sm font-extrabold text-white">Show results</button>}
  </form>;
}
